### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by cespare** [dancannon/gorethink#1]
It makes sense to implement this in the driver, rather than forcing each user to implement it themselves.

We should learn from database/sql and make the pool size configurable from the start.

**Comment by robert-zaremba** [comment]
`database/sql` naming is good to follow.

Regards this issue there are interesting updates in upcoming go 1.2 release, which touch connection pools: http://www.honnef.co/go-tip/2013-09-07/#sql

**Comment by dancannon** [comment]
With help from @crosbymichael I have added connection pools using a similar technique to RedisGo. I will revisit connection pools with the Go 1.2 release and see if there are significant improvements.

@robert-zaremba what do you mean about following the `database/sql` naming?

**Comment by robert-zaremba** [comment]
@cespare said:

> We should learn from database/sql and make the pool size configurable from the start.

I meant that it's a good idea to use the same names as in `database/sql` where the functionality is the same:
- func (*DB) SetMaxIdleConns(n int)
- func (*DB).SetMaxOpenConns(int).
- func (*DB) Ping() error

http://tip.golang.org/pkg/database/sql/#pkg-index

**Comment by dancannon** [comment]
Ah ok, I agree I will look into making these changes later today.

**Comment by dancannon** [comment]
Ok I have added the SetMaxIdleConns and SetMaxOpenConns methods so I am now closing this issue.
