### ISSUE TITLE
Accumulate WriteResponses?

### ISSUE THREAD

**Issue by bryfry** [dancannon/gorethink#104]
Found this useful when I ran a number of operations on a list of things, in my case inserting contents from multiple files.  Might be worth adding as a Method on WriteRewsponse?  I avoided updating the values for FirstError, NewValue and OldValue as I wasn't sure what the most correct information to put in there would be.

```
type myWriteResponse struct {
  r.WriteResponse
}

func (r *myWriteResponse) Accumulate(n r.WriteResponse) {
  r.Errors += n.Errors
  r.Created += n.Created
  r.Inserted += n.Inserted
  r.Updated += n.Updated
  r.Unchanged += n.Unchanged
  r.Replaced += n.Replaced
  r.Deleted += n.Deleted
  r.GeneratedKeys = append(r.GeneratedKeys, n.GeneratedKeys...)
}
```

**Comment by dancannon** [comment]
While I agree that this is useful I am not sure if its something that needs to be included in the driver.

Thanks for showing how to do this though.
