### ISSUE TITLE
Multiple expressions

### ISSUE THREAD

**Issue by acasanova** [dancannon/gorethink#106]
Hi @dancannon, 
I'd like to perform a filter that check for a field's time to be less than an EpochTime. I don't see any examples of a multi filter in the tests so I have the code below but it doesn't compile. 

```
func SearchRecentPublishedDomain(domain string) LeonardoWebpage {
    var err error
    res, err := r.Table("configs").Filter(func(row r.Term) r.Term {
        return row.Field("domain_sld").Eq("domain")
        && row.Field("published_timestamp").Lt(r.EpochTime(time.Now().Unix()))
    }).Run(session)
```

Thanks in advanced

**Comment by dancannon** [comment]
Hi @acasanova,

Because of the way that ReQL compiles functions the use of `&&` is not valid. Instead try using 

``` go
func SearchRecentPublishedDomain(domain string) LeonardoWebpage {
    var err error
    res, err := r.Table("configs").Filter(func(row r.Term) r.Term {
        return row.Field("domain_sld").Eq("domain").And(row.Field("published_timestamp").Lt(r.EpochTime(time.Now().Unix())))
    }).Run(session)
```

Hopefully this should solve your compilation issue.

**Comment by acasanova** [comment]
That worked! Thank you @dancannon
