### ISSUE TITLE
map/reduce example

### ISSUE THREAD

**Issue by bryfry** [dancannon/gorethink#107]
I'm having some issues getting map and reduce to work as expected.  Would it be possible to add an additional example that maps a queried list of rows to a specific value from each (e.g. a "value" field from each row).  

Ideally I'd like to map to a more complex struct with a couple values and the do reductions on that struct.  From how I'm reading the code it looks like this struct might need to be comprised of r.Term types?

Here is the Data Explorer version I am trying to recreate with gorethink:

```
r.db('quiz').table('questions').getAll("Bravo", {index: "category"}).sample(10)
  .map(function(q) {
    return  {sum: q('value'), list:[q('id')]};
  })
  .reduce(function(left, right){
    return r.branch(
      left('sum').add(right('sum')).lt(15),
      {sum: left('sum').add(right('sum')), list: left('list').add(right('list'))},
      {sum: left('sum'), list: left('list')}
      )
  })
```

This results in a nice list of IDs of questions which summed values are less than the (hard coded 15) limit. 

Thanks!

**Comment by dancannon** [comment]
Here is that query converted to Go:

``` go
    r.Db("quiz").Table("questions").GetAllByIndex("category", "Bravo").Sample(10).Map(func(row r.Term) interface{} {
        return map[string]interface{}{
            "sum":  row.Field("value"),
            "list": []interface{}{row.Field("id")},
        }
    }).Reduce(func(left, right r.Term) interface{} {
        return r.Branch(
            left.Field("sum").Add(right.Field("sum")).Lt(15),
            map[string]interface{}{
                "sum":  left.Field("sum").Add(right.Field("sum")),
                "list": left.Field("sum").Add(right.Field("sum")),
            },
            map[string]interface{}{
                "sum":  left.Field("sum"),
                "list": left.Field("sum"),
            },
        )
    })
```

I think this is correct however I have not run the query myself. 

Does this answer your question? If not could you provide more information such as example input/output.

**Comment by bryfry** [comment]
That is perfect.  I was definitely getting hung up in the `map[string]interface{}` areas.  Since they are all r.Terms could it be a `map[string]r.Term`?

This might be a similar question, I'm having trouble accessing and mapping an embedded array from a specific row.  reql below.

```
r.db("exampledb").table("exampletable").get("id")("field_containing_an_array").nth(1)
```

yields  {"Y":1} from a table looking something like this:

```
{"id": "xxxx",
 "field_containing_an_array":[
   {"X",0},
   {"Y",1},
   {"Z",2},
  ],
}
```

Thanks again!  I'm really enjoying gorethink!

**Comment by dancannon** [comment]
`map [string]r.Term` would probably also work however I try to keep my answers as general as possible when responding to issues. 

Regarding your other question I don't quite understand what you mean, what is the issue with the result?

**Comment by bryfry** [comment]
specifically I'm not sure how to write this portion `get("id")("field_containing_an_array")` in gorethink.  I'm not trying to select multiple or by a specific secondary index (GetAll, or GetAllByIndex) but instead to return only that slice field, and then get the nth item from it.

corresponding go structs

``` go
type Example struct {
  Id string
  FieldContainingAnArray []SubExample // the nth value in this slice is what I want to get back
}
type SubExample struct {
  Name string
  Value int
}
```

**Comment by bryfry** [comment]
Right now I'm just stopping after the `get` and then iterating through the resulting type's SubExample slice.  I'd like to avoid doing that extra work when rethinkdb has the ability to get the exact value I'm looking for.

Thanks again!

**Comment by dancannon** [comment]
Ok well because Go doesnt support operator overloading like JS we cannot do `get("id")("field_containing_an_array")` instead we need to do `Get("id").Field("field_containing_an_array")`.

Hopefully that answers your question.

**Comment by bryfry** [comment]
Wow, that one was staring me in the face.  Thanks again,  that worked.
