### ISSUE TITLE
Using secondary index example

### ISSUE THREAD

**Issue by bryfry** [dancannon/gorethink#108]
I've been struggling with the IndexCreateOpts and how they translate into the creation of a secondary index that is made up of two attributes.  From the rethinkdb documentation they show [an example](http://rethinkdb.com/docs/secondary-indexes/javascript/) like below.

``` js
r.table("users").indexCreate("full_name", [r.row("first_name"), r.row("last_name")]).run(conn, callback)
```

How would one go about comprising this query in gorethink?

Thanks!

**Comment by theaidem** [comment]
@bryfry Try this snippet:

```
r.Db("test").Table("users").IndexCreateFunc("full_name", func(row r.Term) interface{} {return []interface{}{row.Field("first_name"), row.Field("last_name")}}).Run(sess)
```

**Comment by bryfry** [comment]
Thanks @theaidem, that worked perfectly.  For anyone here as future reference: here's how you would writeup the query on the secondary multi index:

``` go
r.Db("test").Table("users").GetAllByIndex("full_name", [...]string{"John","Smith"}).Run(sess)
```
