### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by acasanova** [dancannon/gorethink#109]
I wrote a program I intend on running as a init.d process/daemon.  Currently checks the rethinkdb for some content and writes out some files. There's an interval ticker set at 3 mins. I ran it for about a half hour and I recieved the following panic.

```
gorethink: dial tcp x.y.z.d:28015: too many open files
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4b86fe]

goroutine 16 [running]:
runtime.panic(0x5f3ba0, 0x771b13)
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
github.com/dancannon/gorethink.(*Cursor).Next(0x0, 0x581560, 0xc2084bbad0, 0x427cab)
    /Users/acasanova/projects/go/src/github.com/dancannon/gorethink/results.go:87 +0x70e
github.com/dancannon/gorethink.(*Cursor).One(0x0, 0x581560, 0xc2084bbad0, 0x0, 0x0)
    /Users/acasanova/projects/go/src/github.com/dancannon/gorethink/results.go:202 +0x4d
main.SearchRecentlyPublishedDomain(0xc20807a5b0, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/acasanova/projects/go/src/com.drleonardo/publishing/main.go:257 +0x2ae
main.DoEverything(0xc20807a5b0, 0x16)
    /Users/acasanova/projects/go/src/com.drleonardo/publishing/main.go:95 +0x5c
main.main()
    /Users/acasanova/projects/go/src/com.drleonardo/publishing/main.go:83 +0x381
```

I connect to the rethinkdb in main() only once then I make 1 query every 3 minutes.  Below is my query.  

```
//SearchRecentlyPublishedDomain searches for domains published within the past `MinuteIntervalForRecentPublishing` minutes or greater
func SearchRecentlyPublishedDomain(domain string) Webpage {
    var err error
    res, err := r.Table("configs").Filter(func(row r.Term) r.Term {
        return row.Field("id").Eq(domain).And(row.Field("published_timestamp").Gt(time.Now().Add(time.Duration(60*MinuteIntervalForRecentPublishing) * time.Second * -1)))
    }).Run(session)

    if err != nil {
        fmt.Println(err)
    }

    var Webpage LeonardoWebpage

    err = res.One(&Webpage)
    if err != nil {
        fmt.Println(err)
    }

    return Webpage
}
```

The line 257 in the panic is "err = res.One(&Webpage)"

Is there something I'm forgetting to close?

**Comment by acasanova** [comment]
I ended up adding MaxActive:10 and MaxIdle:20 then using the IsNil method and that seem to stop the panics. I'm still curious what your thoughts are. I'm not sure which of the things I changed remediated the issue.
Thanks in advance

**Comment by dancannon** [comment]
Ill try to look at what is causing this bug at the weekend.

**Comment by dancannon** [comment]
I have still not figured out what is causing the error regarding too many open files. When using the `One` function to fetch results this should be handled manually. Are you running any other queries along side this one or are any other errors being returned? 

Currently if any error occurs when fetching the result then the connection is not closed, this is probably not correct behaviour.

Regarding your changes I don't think this is a permanent fix as it is probably just delaying the same result.

**Comment by acasanova** [comment]
Thanks for checking it out further. I couldn't find any other concurrent queries. You were right it did not remediate the issue. Now the panic happens systematically every 15 minutes. I don't get any other errors besides the original. Should I reconnect upon every query? Looking at these suggest that I should close the connection after each query. I'm going to try s.Reconnect and see how that behaves

https://github.com/rethinkdb/rethinkdb/issues/2532 
http://stackoverflow.com/questions/24716642/too-many-open-files-error-with-rethinkdb

**Comment by dancannon** [comment]
When I get some time I will work on reproducing that error and hopefully fixing the underlying bug. 

Unfortunately I recently started a new job and have been busy but I will try to get this sorted as soon as possible.

**Comment by acasanova** [comment]
Congratulations! @dancannon on the new job.

**Comment by dancannon** [comment]
Thanks, unfortunately no RethinkDB :(

**Comment by dancannon** [comment]
I think I have fixed this issue now however I have still not been able to replicate it (I think I have my file descriptor limit set pretty high). Could you please run your code again and see if it still crashes.

The issue was that I was running a NoReply wait query when closing the query however I was not using the same connection which meant things were not being closed properly and the NoReply query was not doing what it was meant to do anyway.

**Comment by acasanova** [comment]
I rebuilt the application with your latest commit and deployed. I will keep you posted. Thank you for looking into this.

**Comment by dancannon** [comment]
Has the error reappeared or can this now be closed?

**Comment by acasanova** [comment]
Hey @dancannon, I still recieve these messages in the logs. 

```
gorethink: dial tcp {IP}:28015: too many open files.  
```

But I haven't been able to track down a stack trace on it yet.  I added some code to reconnect on panic when querying the database. So since then the code doesn't die. But it might be bad practice to do that.

```
//SearchRecentlyPublishedDomain searches for domains published within the past `MinuteIntervalForRecentPublishing` minutes or greater
func SearchRecentlyPublishedDomain(domain string) LeonardoWebpage {
    var err error
    var leonardoWebpage LeonardoWebpage
    defer func() {
        if r := recover(); r != nil {
            log.Printf("__Error__: %s\n %s\n\n", r, debug.Stack())
            ConnectToRethinkdb()
            SearchRecentlyPublishedDomain(domain)
        }
    }()

    res, err := r.Table("configs").Filter(func(row r.Term) r.Term {
        return row.Field("id").Eq(domain).And(row.Field("published_timestamp").Gt(time.Now().Add(time.Duration(60*MinuteIntervalForRecentPublishing) * time.Second * -1)))
    }).Run(session)

    if err != nil {
        fmt.Println(err)
    }

    if res.IsNil() {
        log.Printf("No records for %s in the last few minutes", domain)
        return leonardoWebpage
    }

    err = res.One(&leonardoWebpage)
    if err != nil {
        fmt.Println(err)
    }

    return leonardoWebpage
}
```

I'm using nohup for the daemon so i think its suppressing the stack trace for some reason. I'll try to get that for you tomorrow.

**Comment by acasanova** [comment]
I ran the following commands to check how much I'm going over the file descriptor count.

I checked on the amount of open files based on PID
![image](https://cloud.githubusercontent.com/assets/2922800/4099937/7c8bc5f4-3077-11e4-99ae-6be7242dbf5e.png)

Here are my limits
![image](https://cloud.githubusercontent.com/assets/2922800/4099947/a5739d66-3077-11e4-9676-7ed264e739f0.png)

I ran ulimit -n 4096 and emptied the logs to see if there was any change, I'll report my findings tomorrow.

**Comment by dancannon** [comment]
Ok thanks, I am currently working on updating to v1.14 and as part of that I have started using the JSON protocol and have replaced my connection pool code with https://github.com/fatih/pool.

Some of these changes might fix this issue however I am still not 100% sure what is causing it.

**Comment by acasanova** [comment]
I think we might be able to close this. I reduced the amount of queries running but i afraid I might see this again once I start seeing more traffic. I was running around 200 queries every 3-4 minutes. now its 1 query every 3-4 minutes. The "too many open files" error has subsided. I bumped up the resources on the database server. So for now it looks pretty stable.

**Comment by dancannon** [comment]
Ok ill close this now, if you manage to replicate this issue (or you believe it to be completely fixed in the future) could you please let me know, thanks.
