### ISSUE TITLE
change versioning numbers to match gopkg.in

### ISSUE THREAD

**Issue by robert-zaremba** [dancannon/gorethink#111]
According to http://gopkg.in:

> The number used in the gopkg.in URL looks like "v1" or "v42", and represents the major version for the Go package. No incompatible changes should be done to the package without also changing that version, so that packages and applications that import the package can continue to work over time without being affected by broken dependencies.

Currently we are not able to use gorethink with gopkg.in, because point releases (0.2, 0.3) provide breaking changes. Would be useful to provide versioning supported by gopkg.in

**Comment by dancannon** [comment]
This is something I have chosen to do on purpose. 

Neither this driver nor the database are currently stable. Once RethinkDB reaches 2.0 and this driver has been updated I will release GoRethink v1.0.

**Comment by robert-zaremba** [comment]
then it's hard to fix the version of the package. To be 100% one will need to fork the version and change all import paths of sub-packages (encoding and ql2)

**Comment by timshannon** [comment]
Take a look at [godep](https://github.com/tools/godep).  It basically does this for you, and is a good idea especially when dealing with external libraries on a bigger project.
