### ISSUE TITLE
OrderBy doesn't handle index correctly

### ISSUE THREAD

**Issue by robert-zaremba** [dancannon/gorethink#114]
I'm doing this query:

```
cursor, err := myTable.Between(
    []interface{}{product, market, from},
    []interface{}{product, marketEnd, to}, rdb.BetweenOpts{Index: "pro-mar-t"}).
    OrderBy(rdb.OrderByOpts{Index: rdb.Desc("pro-mar-t")}).
    Filter(Map{"fla": Map{"h": false}})
    .Run(session)
```

Which produced the following error (`err` from above).

```
Unable to get quotes from DB gorethink: Expected type STRING but found OBJECT. in: 
r.Table("quote").Between(["RYEUKR20", "", 0], ["RYEUKR20", "\xff", 17179869180], index="pro-mar-t").OrderBy(index={}).Filter({fla={h=false}}).Limit(200)
```

The issue come when updating to new version of rethinkdb (1.12.5 -> 1.13.3) and gorethinkdb (0.2 -> 0.3.1) driver, the only change in that query was to wrap index into  `OrderByOpts` structure. Previously the OrderBy part was:

```
OrderBy(map[string]interface{}{"index": rdb.Desc("pro-mar-t")})
```

and it worked.

**Comment by dancannon** [comment]
This bug occurred because the code which encodes the optional argument structs into maps ignored `r.Term`s.

**Comment by robert-zaremba** [comment]
Thanks for looking after it!
