### ISSUE TITLE
Potential infinite loop in Connection.SendQuery

### ISSUE THREAD

**Issue by beefsack** [dancannon/gorethink#119]
It appears if there is an error writing the query token to the connection in [SendQuery](https://github.com/dancannon/gorethink/blob/v0.4.1/connection.go#L148), it [calls close on the connection](https://github.com/dancannon/gorethink/blob/v0.4.1/connection.go#L166), which [calls NoreplyWait](https://github.com/dancannon/gorethink/blob/v0.4.1/connection.go#L260), which [calls SendQuery again](https://github.com/dancannon/gorethink/blob/v0.4.1/connection.go#L277) and begins an infinite loop.

Obviously this loop is only triggered in failure states but it can make it a little tricky to debug issues.

I'm currently trying to come up with a minimal reproduction and will update this issue if I can make one.  This issue is popping up in one of my apps but the large call stack makes it a little hard to figure out exactly what's causing it from my app.

**Comment by beefsack** [comment]
I'm having trouble reproducing, I've got a minimal test which repeatedly queries a table then closes the cursor but it doesn't seem to be triggering it.  The error that was initially triggering it was `use of closed network connection` so it's even possible a local configuration on my machine is killing the connections if it's running out of resources or hitting some RethinkDB limits.

If I can figure out a reliable way to reproduce I'll reopen.

**Comment by dancannon** [comment]
Im reopening this as I believe this might actually be part of the reason behind #109 or an issue caused by the changes in v0.4.1.

At the very least there is clearly an issue with my connection closing logic.

**Comment by beefsack** [comment]
Note that in my testing I had to go back to v0.3.1 for the issue to go away.  Removing all of my manual cur.Close() calls in my code seems to have worked around it for later versions of the library in my app, as I believe One and All close the cursor internally anyway and that's all I'm using.

**Comment by dancannon** [comment]
Interesting, in that case it makes it even more likely that this is the same issue causing #109.

**Comment by dancannon** [comment]
Could you check the https://github.com/dancannon/gorethink/tree/hotfix/v0.4.2 branch and see if you still have this issue (or any other issues)

**Comment by beefsack** [comment]
Hi @dancannon, looks like we might have a git conflict in the source: https://github.com/dancannon/gorethink/blob/hotfix/v0.4.2/connection.go#L282

Had a quick look but not 100% sure how the two parts should be merged.

**Comment by dancannon** [comment]
Sorry about that, I think I `git stash pop`'d too many times. Could you check again

**Comment by beefsack** [comment]
No worries :smile: and the original issue is fixed in hotfix/v0.4.2, cheers!

**Comment by dancannon** [comment]
Awesome, I will double check this branch and merge into master either this evening or tomorrow.
