### ISSUE TITLE
OldValue and NewValue empty when padding ReturnChanges

### ISSUE THREAD

**Issue by beefsack** [dancannon/gorethink#120]
Hi @dancannon, it appears the ReturnChanges option isn't returning OldValues and NewValues, I've created [an example gist](https://gist.github.com/beefsack/e212098e908ecce78c8b).

It appears when looking at the data explorer those values are being returned under a `changes` array, with each element having a `new_val` and an `old_val` field, so not sure if it's a structure mismatch causing it.

Example data explorer query and response:

``` JavaScript
r.db('test').table('blah').insert([{thing: "bacon"}, {thing: "cheese"}], {returnChanges: true})
```

``` JSON
{"changes":[{"new_val":{"egg":"bacon","id":"44fbf427-69c7-40fa-a97c-a0e6ac6f3efd"},"old_val":null},{"new_val":{"egg":"cheese","id":"d0ce6d35-49d0-4976-8d4a-4f75777e6b0e"},"old_val":null}],"deleted":0,"errors":0,"generated_keys":["44fbf427-69c7-40fa-a97c-a0e6ac6f3efd","d0ce6d35-49d0-4976-8d4a-4f75777e6b0e"],"inserted":2,"replaced":0,"skipped":0,"unchanged":0}
```

**Comment by dancannon** [comment]
Yeah this is a structure mismatch. I guess they must have changed the return values with one of the recent releases. I will update this later today.

**Comment by dancannon** [comment]
Ok this is now fixed in `hotfix/v0.4.2`. 

After doing some many releases in a short amount of time I have decided to wait until the end of the week to release this version.

**Comment by beefsack** [comment]
Cheers, confirmed working :+1: super quick response too, created the job when I went to bed and was fixed when I got up!

Will run with hotfix/v0.4.2 for now, seems to be working well for me at the moment.

**Comment by dancannon** [comment]
This fix is now in master
