### ISSUE TITLE
Docs for Run() mention nonexistent Scan() function

### ISSUE THREAD

**Issue by evmar** [dancannon/gorethink#122]
The docs for `Run()` say:

```
for rows.Next() {
    doc := MyDocumentType{}
    err := r.Scan(&doc)
        // Do something with row
}
```

but `Scan()` doesn't exist.

(BTW, if you put a function named like `func ExampleFoo_bar()` in the unit test, godoc will both verify it still compiles and add it to the docs as a test.)

**Comment by dancannon** [comment]
Thanks for pointing out this documentation error, I will try and get this sorted this evening.

Also what do you mean about the examples, I am aware that they are treated as tests, are they failing for you?
