### ISSUE TITLE
API for iteration shouldn't reuse object

### ISSUE THREAD

**Issue by evmar** [dancannon/gorethink#123]
(This isn't exactly a bug, but more of a request for comment.)

The cursor `Next()` function looks like:

```
func (c *Cursor) Next(result interface{}) bool {
```

This function can't know how to reset its parameter to the zero value.  I think this means if you use the same object twice in `Next()`, like:

```
var foo MyFoo
c.Next(&foo)
// ...use foo
c.Next(&foo)
// ...use foo
// more realistically, in a for loop
```

Then there's no way to ensure that fields set by the first `Next` are cleared before the second.

So the only reasonable way to use this API is like:

```
for {
  var foo MyFoo
  if !c.Next(&foo) {
    break
  }
  // use foo
}
```

Which doesn't seem intentional.

**Comment by dancannon** [comment]
Thanks, you raise a very good point. When using next the value should probably be zeroed first. 

I will fix this issue this evening.

**Comment by robert-zaremba** [comment]
For me it's not an issue. This is the way how this driver works. Other drivers works in the same way. Currently if you want to zero value before then you should reset it by yourself or create a new value.

**Comment by dancannon** [comment]
I am actually of the opinion that the driver should zero the value. That way the result represents exactly what is in the database, if you do not zero the value first then you might get into situations where you access a value that doesnt exist in the currently selected row so you use the value from the previous row. In my opinion this is pretty dangerous and incorrect behaviour.

What I could do is add an optional argument to the Next method which will allow you to override the default functionality.
