### ISSUE TITLE
ReturnChanges seems doesn't work.

### ISSUE THREAD

**Issue by 3d0c** [dancannon/gorethink#124]
After updating to 1.14 version of Rethink and gorethink, queries that change data stop returning new values. I'm not sure, that i'm using it right, but i couldn't find test cases and examples for ReturnChanges.

``` go
    payload := &User{
        Name: "oops",
    }

    result, err := r.Table("users").Insert(payload, r.InsertOpts{ReturnChanges: true}).Run(session)
    if err != nil {
        log.Fatalln(err)
    }

    response := &r.WriteResponse{}

    if err = result.One(response); err != nil {
        log.Fatalln(err)
    }
```

Response is `&{0 0 1 0 0 0 0 0 [d75ae954-dc24-4115-a2a4-fd31520bb672]  <nil> <nil>}`, NewValue is nil.  
It works well in 1.13...

**Comment by dancannon** [comment]
Hi Alex, This is a known issue and has been fixed in the branch `hotfix/v0.4.2`. I will be merging this branch to master soon.

**Comment by dancannon** [comment]
This fix is now in master

**Comment by 3d0c** [comment]
Great! Thanks.
