### ISSUE TITLE
Terrible performance; extreme cpu usage; degrades further over time

### ISSUE THREAD

**Issue by wildattire** [dancannon/gorethink#125]
We are experiencing extremely bad performance with this driver, and it's easily reproducible.

This is using the most recently committed gorethink driver and RethinkDB 1.14.1
The platform is a digitalocean host running Ubuntu 14.04 with 4 cores and 8GB ram, but I've reproduced the same thing on other hosts with varying configurations.

A simple program to insert 30000 tiny test documents using 3 concurrent functions inserting 10000 documents each completes in:

real    7m0.511s
user    10m56.033s
sys 0m47.415s

Which works out to be 71 documents per second. 

And during this time CPU usage for go, not so much rethink, goes nuts:

![cpudamn](https://cloud.githubusercontent.com/assets/389543/4287826/a614d550-3da6-11e4-9ea2-e0c15bee3fed.png)

The really odd thing is that the performance gets worse as time goes on.  It starts initially at around 300 ops/s and near the end of the test, the performance drops down to about 25 ops/s:

![performance](https://cloud.githubusercontent.com/assets/389543/4287830/b909a7c6-3da6-11e4-9742-0297cb250424.jpg)

I am posting this issue in gorethink instead of rethinkdb primarily because of the CPU - the driver is burning cpu like the devil inserting just a few thousand tiny documents.

Here is the small app used in this test:

```
package main

import "log"
import "strconv"
import "runtime"
import rdb "github.com/dancannon/gorethink"

type test_document struct {
        Id       string `gorethink:"name"`
        ParentId string `gorethink:"parent_id"`
        Username string `gorethink:"username"`
        Status   int    `gorethink:"status"`
}

func he(cur *rdb.Cursor, err error) {
        if err != nil {
                panic(err)
        }
}

func main() {

        runtime.GOMAXPROCS(2)

        log.Printf("Creating DB...")
        opts := rdb.ConnectOpts{
                Address: "localhost:28015",
                MaxIdle: 10,
        }

        ses, err := rdb.Connect(opts)
        if err != nil {
                panic(err)
        }

        _, _ = rdb.DbDrop("perf_test").Run(ses)

        _, err = rdb.DbCreate("perf_test").Run(ses)
        if err != nil {
                panic(err)
        }

        ses.Use("perf_test")

        tcopts := rdb.TableCreateOpts{PrimaryKey: "id", Durability: "soft"}

        log.Printf("Creating Table...\n")

        he(rdb.Db("perf_test").TableCreate("users", tcopts).Run(ses))
        he(rdb.Db("perf_test").Table("users").IndexCreate("username").Run(ses))
        he(rdb.Db("perf_test").Table("users").IndexCreate("parent_id").Run(ses))

        log.Printf("Populating table...\n")

        go what(0, 10000, ses)
        go what(10000, 20000, ses)
        what(20000, 30000, ses)

        log.Printf("Done.\n")

}

func what(begin int, end int, ses *rdb.Session) {
        for i := begin; i < end; i++ {
                user := test_document{
                        Id:       strconv.Itoa(i),
                        Username: strconv.Itoa(i),
                        ParentId: strconv.Itoa(i - 1),
                        Status:   0,
                }
                rdb.Table("users").Insert(&user).Run(ses)
        }
}
```

**Comment by wildattire** [comment]
As a quick followup to this, I wrote an analogous test app that uses mongodb and the mgo driver to insert the same number of the same type of documents, on the same host. It completed in eight seconds, only two of which were user cpu.

Although I fully understand these dbms are not at all the same and they have entirely different goals, the fact that we're looking at more than two orders of magnitude difference in cpu burn on the client side is very worrisome.

**Comment by dancannon** [comment]
Ok there is clearly a very big issue here. Marking as high priority and will look into the cause ASAP.

**Comment by robert-zaremba** [comment]
I've also found this issue during 0.2\* to 0.3 updgrade in one of our batch loaders. Unfortunately I didn't have a time to extract a problem. If you will need more examples I can prepare a snippet of our case, but I guess it will just overlap with this one.

**Comment by timshannon** [comment]
I can't speak to the CPU issues you're seeing, but the Insert performance
is something that is known, which may be what you are referring to as
"different goals":
http://www.rethinkdb.com/docs/troubleshooting/#my-insert-queries-are-slow.-how-can-i-speed-t

**Comment by wildattire** [comment]
@dancannon thanks.

**Comment by dancannon** [comment]
I have spent a couple of hours this evening profiling the driver and I believe the major cause of the high CPU usage is the encoding package. I will have another look at this tomorrow hopefully however I have been planning on rewriting this entire section so it might take me a week or two to get this sorted depending on how I proceed. I apologise for the issues this might cause you.

That being said as @timshannon mentioned the Insert speed in RethinkDB can be pretty slow so I am not sure if there is an issue causing the slow Insert performance in the driver. Hopefully this will be clearer once I have fixed the issues with encoding.

**Comment by robert-zaremba** [comment]
The `durability` option is set to _soft_ so inserts should be fast. I think one can use `Exec` to test only the driver site performance.

**Comment by dancannon** [comment]
Unfortunately I have been busy at work and have not had time to look at it properly yet. Will probably have to wait until the weekend.

Sorry for the delay.

**Comment by dancannon** [comment]
So to give you an update I believe that the code that deals with encoding pseudo-types is causing this issue. Unfortunately it does not appear to be a quick fix as the reason this code is causing such high CPU usage is because of the use of reflection. I will continue looking for alternate solutions but it does not look good.

Unless I can find another fix I might need to move away from using reflection to determine if a value should be decoded as a pseudo-type, some possible solutions are:
- Change the drriver to only accept certain types for pseudo-types  values which would mean that driver could use type assertions (for example to insert a time value into the DB the driver would only check for `time.Time`).
- Add `Marshaler` and `Unmarshaler` interfaces similar to the encoding libraries which would encode the values to GoRethink `Term`s. The driver could then have a set of build in types (Such as r.Time) which would implement those interfaces.

I am currently leaning towards using the interface solution as it is the simplest but it would mean that code that used the driver would likely have to use quite a bit of casting. 

What does everybody think of the above solutions?

**Comment by pengux** [comment]
@dancannon +1 on the interface solution

**Comment by dancannon** [comment]
I have changed the logic for detecting psuedo-types slightly and encoding should now have slightly better performance. 

Could you check your tests against the https://github.com/dancannon/gorethink/tree/hotfix/v0.4.3 branch @wildattire and see if the CPU usage is slightly lower.

**Comment by evmar** [comment]
HEAD (3f5ff83b3a590e175ac870f8d2d5ad9d3ddebcd8) is about 12ms per insert in a small test app.

hotfix/v0.4.3 (f76b7e6a55d98a7a7d79fd93d526339a8b9b951c) is about 2ms per insert in the same app.

**Comment by evmar** [comment]
Regarding which API to provide, one way to think about it is: which one can be implemented in terms of the other? which one is faster?

**Comment by dancannon** [comment]
Ok that's a good sign. What kind of performance would you be expecting on your setup?

**Comment by evmar** [comment]
I'm not sure.  I was a little surprised that inserts are CPU-limited at the client side.  Running rethink and my Go client on the same machine, the client pegs a CPU at 100% and the rethinkdb process hovers around 30%, which indicates rethink's deserialization+insertion logic is something like 3x as fast as gorethink's encoding logic.

**Comment by evmar** [comment]
From a run of my test program (with the fixed branch, but inserting a larger amount of data):

```
2014/09/21 16:54:41 12392 inserts in 1m30.659141437s
2014/09/21 16:54:41 136.7 inserts per s
2014/09/21 16:54:41 7.315941ms per insert
```

Profiler says `encoding.encode` is ~97% of the CPU time.

The last percentage here is the time in that function and code that it calls.

```
Total: 9000 samples
    2883  32.0%  32.0%     7649  85.0% github.com/dancannon/gorethink.func·003
    1031  11.5%  43.5%     8692  96.6% github.com/dancannon/gorethink/encoding.encode
     951  10.6%  54.1%      951  10.6% reflect.haveIdenticalUnderlyingType
     849   9.4%  63.5%     2140  23.8% reflect.convertOp
     634   7.0%  70.5%     1288  14.3% assertI2Tret
     465   5.2%  75.7%     4184  46.5% reflect.(*rtype).ConvertibleTo
     368   4.1%  79.8%      654   7.3% copyout
     340   3.8%  83.6%      340   3.8% reflect.implements
     296   3.3%  86.9%      296   3.3% reflect.Value.Kind
     291   3.2%  90.1%     1579  17.5% runtime.assertI2T
```

**Comment by evmar** [comment]
I think the strangest part is how it seems to get slower over time. I would think that might be due to GC or something but that doesn't show up in the profiles anymore.

**Comment by dancannon** [comment]
Hmm I was hoping my fixes would prevent encoding slowing down over time. I will have another look over the code however I think this just shows how badly the driver needs to move away from reflection (where possible).

I am currently leaning towards the interface solution as it allows for far more flexibility(regarding supporting more psuedo-types) than both the current solution and the other proposed solution while only requiring slightly more work from anyone using the driver.

**Comment by kofalt** [comment]
@dancannon Could you elaborate on what you've been referring to regarding increased work / casting? When I took a look at your hotfix branch the tests didn't seem any more complicated.

Maybe an example?

**Comment by dancannon** [comment]
Sure so every time you insert a value into the table that value is encoded. This encoding step is basically used to check for any psuedo-types (such as times). When encoding values the driver recursively checks each node of the data structure checking for the mentioned pseudo-types. Unfortunately I use reflection for this and it turns out that using reflection the way I have done it is pretty slow. 

That being said it is also pretty likely that there is a flaw in my logic causing this slowdown since the driver already uses the encoding/json package the encode the query tree for the JSON protocol and the current fix only solved part of the issues.

Regarding this fix it solved a GC issue. I was fetching the `reflect.Type` value of `time.Time` and `r.Term` for every step of the encoding process which was both unnecessary work and meant that the values needed to be garbage collected.

Does this answer your question @kofalt or have I misunderstood you?

**Comment by kofalt** [comment]
I think so. I was mainly asking after how much casting would typical usage of the driver require after this fix. Sounds like it won't be a huge concern.

**Comment by dancannon** [comment]
Ah I see, I have not yet implemented any of the solutions I mentioned above so honestly I am not yet sure. It would probably mean doing something like the code below however this is just a guess at how I would change things:

``` go
type Test struct {
    Time r.Time
}

t := Test{
    Time: r.Time(time.Now()),
}
```

**Comment by kofalt** [comment]
That seems reasonable if it'll improve performance; if I recall correctly the official python driver expects you to work the same way. Unfortunate that you have to rec-cast with a static language though.

I don't suppose struct annotations would help? The JSON encoder takes a variety of instructions via annotations, is querying that kind of data easier than a full reflection check?

``` go
type Test struct {
    Time r.Time `gorethink:time`
}
```

**Comment by dancannon** [comment]
Thats also a pretty good solution @kofalt. It should have the same result as interface solution but possibly with better performance and might also remove the need to have a set of type aliases (so you could use time.Time). I will definitely have a look into it.

**Comment by kofalt** [comment]
> One issue I have discovered with the interface solution is that 

Guessing you lost some of your comment there :)

**Comment by dancannon** [comment]
Ooops, I have removed that now since I think I have found a workaround.

**Comment by dancannon** [comment]
So I have some good news, I believe that I have tracked down the cause of the performance issues. There is still quite a bit of work to be done tidying up my fixes and I also want to have a look at the decoding performance (for scanning the response into structs). But I should be able to release an update for 1.15 soon.

The first issue was that I was recalculating how to encode values every time, after looking at how the encoding/json package caches this the CPU usage was greatly reduced. 

Unfortunately the writes/second were still very low, after more profiling I discovered that the use of a connection pool meant that the driver was reconnecting very often, even after adjusting the pool parameters performance did not improve very much. The use of connection pools have also caused some issues in the past with how RethinkDB handles connections so I think it makes sense to remove pools (at least for now).

After I have made these changes I appear to get write times very similar to the python driver and the CPU usage is much lower.

**Comment by kofalt** [comment]
Great news! Two questions.

Will the removal of connection pools cause concurrent use to be serialized? I'm using gorethink in a web server environment (one goroutine per request, as usual) and blocking on one request at a time would be disasterous. I'd also rather not instantiate & tear-down an RDB connection every request, so I'm hoping there's a solution for this use case.

Second & off-topic: is the RDB driver protocol forward-compatible? In other words, is it safe to use 1.15 with the current `master` of gorethink?

**Comment by dancannon** [comment]
So currently the removal of the connection pools has actually completely broken concurrent use. As you mention web servers are a pretty big use case for databases so I will need to fix this issue before I can release the fix (this is what I am working on at the moment).

In answer to your second questions the driver should be forward-compatible however I have not tested it completely but in the past I have not heard of any major issues.

**Comment by kofalt** [comment]
Sounds good, I'll hold off on updating gorethink until it's ready for concurrent usage.

I greatly appreciate your high-quality responses, keep up the good work :)

**Comment by dancannon** [comment]
Unfortunately I have not yet sorted the connection pool issue but I wanted to get a start on updating the driver for 1.15 and I also want to confirm that I have actually fixed this issue so I have split the issues.

@wildattire could you please check this branch https://github.com/dancannon/gorethink/tree/feature/cpu_encoding and check specifically for the crazy CPU usage, the writes/second should be a bit higher but not as high as expected.

**Comment by Coccodrillo** [comment]
I noticed the same issue, so i made a small comparison using your new branch and a node.js with official driver as a comparison.

Gorethink master (no concurrence):
4000 records inserted in 27.390637827s
4000 records inserted in 1m14.840480981s
4000 records inserted in 2m1.082798771s
4000 records inserted in 2m48.687530684s
4000 records inserted in 3m34.83625204s
4000 records inserted in 5m17.609314463s
4000 records inserted in 5m10.727135921s
4000 records inserted in 6m1.335249608s
4000 records inserted in 6m53.666165054s
4000 records inserted in 7m43.926289049s
4000 records inserted in 8m21.226678052s
4000 records inserted in 9m10.126476118s
4000 records inserted in 10m16.812789573s
1750 records inserted in 5m11.280426307s
Inserts completed in 1h25m25.92696984s

Gorethink feature/cpu_encoding (no concurrence):
4000 records inserted in 2.687935834s
4000 records inserted in 2.733651902s
4000 records inserted in 2.825022732s
4000 records inserted in 2.664042783s
4000 records inserted in 2.65455497s
4000 records inserted in 2.792311471s
4000 records inserted in 2.831056407s
4000 records inserted in 2.850167456s
4000 records inserted in 2.861331707s
4000 records inserted in 2.830770278s
4000 records inserted in 2.938456994s
4000 records inserted in 3.152420089s
4000 records inserted in 3.449934522s
4000 records inserted in 2.784680676s
1750 records inserted in 1.181494413s
Inserts completed in 46.228936526s

Node.js serial with promises:
4000 records inserted in 2.840s
4000 records inserted in 2.956s
4000 records inserted in 2.971s
4000 records inserted in 3.141s
4000 records inserted in 3.246s
4000 records inserted in 3.087s
4000 records inserted in 3.103s
4000 records inserted in 3.114s
4000 records inserted in 3.087s
4000 records inserted in 3.373s
4000 records inserted in 3.267s
4000 records inserted in 3.314s
4000 records inserted in 3.376s
4000 records inserted in 3.170s
1750 records inserted in 1.375s
Inserts completed in 52.157s

The cpu hit 100% for the entire duration on master, while it didn't reach 25% on the new branch. The performance is roughly equivalent to node.js so it looks like this fixes the problem for non-concurrent usage.

**Comment by dancannon** [comment]
Ok thats great thats the result I was expecting and hoping for. Keep an eye on #130 which should fix the concurrency issues.

I will see if a couple more people get the same results before closing this issue since it is such a big issue. 

Thanks for replying.

**Comment by kofalt** [comment]
Just to make sure you weren't waiting on me: I don't have a use case that experiences this problem & so defer to @Coccodrillo's benchmark. I did a quick code review, and the branch diff looks fine.

**Comment by dancannon** [comment]
Thanks everybody, I will be closing this and releasing a pre-release version of the driver with support for RethinkDB v1.15 later today.
