### ISSUE TITLE
The field value with name specified in tag value can't be decoded back. 

### ISSUE THREAD

**Issue by AlexLuya** [dancannon/gorethink#128]
I have a struct like like this:

``` go
type Msg struct{
    Id                 string `gorethink:"id"`
    Name           string `gorethink:"Type"`
}
```

and save this:

``` go
Msg{Id:"msg-001",Name:"DELETE"}
```

to rethinkdb,and check in Rethink's web UI,found record saved as I expected:

``` json
{
    "Id":"msg-001",
   "Type":"DELETE"
}
```

then I retrieve it and decode it to golang struct,I got this:

``` go
Msg{Id:"msg-001",Name:""}//<-----------------here the value of "Name" lost
```

the value of field "Name" didn't get decoded back.Is this a bug or does I make a mistake?

**Comment by dancannon** [comment]
Currently prioritising #125 and v1.14 release. Will look at this soon I promise!

**Comment by ghost** [comment]
@AlexLuya, could you please show the code responsible for getting result from DB?

**Comment by AlexLuya** [comment]
Actually,I prepended this Msg to an embed array like this

``` go
func main() {
    res, err := rt.Table(s.Table).Get(modelId).Update(map[string]interface{}{
        "Messages": rt.Row.Field("Message").Prepend(Msg{Id: "msg-001", Name: "DELETE"}),
    }, rt.UpdateOpts{ReturnChanges: true}).RunWrite(s.Session)

    if err != nil || es.Replaced == 0 {
        return err
    }

    change := res.Changes[0]

    PropertyCopy(change.NewValue, pointer)
}

func PropertyCopy(from, to interface{}) interface{} {

    bytes, err := json.Marshal(from)

    if err != nil {
        panic(err)
    }

    if err = json.Unmarshal(bytes, to); err != nil {
        panic(err)
    }

    return to
}
```

I think this "PropertyCopy(change.NewValue, pointer)" caused the problem,How can I decode change.NewValue correctlly?

**Comment by dancannon** [comment]
@AlexLuya Could you please format your issues correctly and check for syntax errors in future.

I have corrected your comments above but please see https://help.github.com/articles/github-flavored-markdown#fenced-code-blocks for how to add code blocks.

**Comment by ghost** [comment]
@AlexLuya, `res.Changes` contains a list of maps. You  can get access to your data directly like `res.Changes[0].NewValue["Type"]` or `res.Changes[0].NewValue["id"]`.

Not sure whether marshaling and then again unmarshaling data just to bind `map` to your `Msg` type is a very effective solution. Anyway, it doesn't work for you because you have to define `json` tags like:

``` Go
type Msg struct{
    Id   string `gorethink:"id" json:"id"`
    Name string `gorethink:"Type" json:"Type"`
}
```

This is by the way related to #126.

**Comment by dancannon** [comment]
I am closing this in favour of #126 since my answer there should answer this, if not let me know.
