### ISSUE TITLE
Missing r.Row()

### ISSUE THREAD

**Issue by KenTorres** [dancannon/gorethink#133]
In the python driver, I might do something like:

``` python
r.table(table).get(id).update({
   key: r.row[key].append(value)
}).run(conn))
```

To add `value` to an array of name `key`.
In the [gorethink documentation](http://godoc.org/github.com/dancannon/gorethink#Term.Append) I can find `Append` but not `Row`.

Am I missing something? How do I manipulate a document key with gorethink?

**Comment by dancannon** [comment]
Hi, try the code below. The driver implements the function `Field` instead of `(key)` because Go does not support operator overloading. Hope that answers your question.

``` go
r.Table(table).Get(id).Update(map[string]interface{}{
    "key": r.Row.Field(key).Append(value),
}).Run(conn)
```

**Comment by KenTorres** [comment]
Oh! Missed that entirely. Thanks!
