### ISSUE TITLE
Error saving []byte property of struct

### ISSUE THREAD

**Issue by beefsack** [dancannon/gorethink#135]
I'm not entirely sure this is meant to be supported, but writing structs with a `[]byte` member is failing.  Rethinkdb `--version` output is `rethinkdb 1.15.1 (GCC 4.9.1)`.

Example: https://gist.github.com/beefsack/9274ba72804e39736f27

Example struct:

``` go
type Blah struct {
    Id   int    `gorethink:"id,omitempty"`
    Name []byte `gorethink:"name"`
}
```

Output:

```
$ go run main.go 
2014/10/20 16:49:43 Testing insert
2014/10/20 16:49:43 gorethink: Expected type STRING but found PTYPE<BINARY>. in: 
r.Db("test").Table("blah").Insert({id=1, name={$reql_type$="BINARY", data=r.binary(<data>)}})
exit status 1
```

**Comment by dancannon** [comment]
@beefsack I have solved the initial problem which caused this issue however I have found more issues while testing. It might take a couple more days before I can get a proper fix pushed to master.

Sorry for the delays.

**Comment by beefsack** [comment]
Hi @dancannon, no worries about the delay, I've reverted to the version supporting 1.14 and is working as it did before.  Thanks for having a look.

**Comment by dancannon** [comment]
This should now be fixed, could you confirm?

**Comment by beefsack** [comment]
Working brilliantly, cheers! :+1:
