### ISSUE TITLE
Empty slice won't be unmarshalled to empty slice but nil

### ISSUE THREAD

**Issue by AlexLuya** [dancannon/gorethink#138]
I have struct like this:

``` go
type Test struct{
    Items  []string
}
```

and if saving this 

``` go
 Test{[]string{}}
```

to rethinkdb,then retrieve it back,I want to and will get

``` go
  {Items:[]string{}}
```

, but after updating to  latest version,I will get

``` go
  {Items:nil}
```

,cause many tests fail.I think previous version's behavior obeyed the intention of programmer and this new change doesn't.

**Comment by dancannon** [comment]
Hi Alex,

Thanks for creating this issue, luckily I am redoing the encoding/decoding process this week so I will add a new test and make sure that this functionality is not removed again.

I will let you know when I have got something working.

**Comment by AlexLuya** [comment]
Thanks

**Comment by AlexLuya** [comment]
Is there any way to install past working version?

**Comment by dancannon** [comment]
@AlexLuya I decided that it was going to take me too long to release the next version so I fixed this issue in master. I have also added this test https://github.com/dancannon/gorethink/blob/master/encoding/decoder_test.go#L148

Hope this solves your issue if not let me know.
