### ISSUE TITLE
Can you write one complete example in docs?

### ISSUE THREAD

**Issue by ekanna** [dancannon/gorethink#17]
Hi @dancannon 

It will be great if you can provide one complete example where user can just copy and paste the code and start using the driver!

Thanks

**Comment by dancannon** [comment]
This is definitely something I am planning on. I will look into getting a simple example application working soon.

**Comment by ekanna** [comment]
My complete example for the benefit of others like me!

``` go
package main

import (
   r "github.com/dancannon/gorethink"
   "fmt"
)

var session *r.Session

func init(){
   var err error
   session, err = r.Connect(map[string]interface{}{
      "address":     "localhost:28015",
      "database":    "test",
   })  
   if err != nil {
      fmt.Println(err)
      return
   }   
}

// uppercase for struct fields is necessary for scanning later
type Person struct {
   Id int 
   Name string
   Place string
}

func main(){
   // fetch all records from "persons" table
   rows,_ := r.Table("persons").Run(session)
   var persons []Person
   for rows.Next(){
      var p Person
      err := rows.Scan(&p)
      if err != nil {
         fmt.Println(err)
         return
      }   
      persons = append(persons, p)
   }   
   fmt.Println(persons)
}

```

**Comment by dancannon** [comment]
Thanks for this, Ill add this to the repo wiki

**Comment by dancannon** [comment]
I am aiming to create a more full featured example application so I will leave this issue open for now.

**Comment by ekanna** [comment]
Great! Waiting to see your full featured example application!

**Comment by dancannon** [comment]
Ok so I have created a simple Todo app based on http://todomvc.com. If you guys could have a look at the code and let me know if see any problems that would great.

https://github.com/dancannon/GoRethink_TodoDemo

**Comment by elithrar** [comment]
@dancannon Fantastic, thanks Dan. I'll take a look over it as I port my code (slowly!) from rethinkgo to gorethink—it's a good example of best practice for this driver.

One question that I have from it though: is there a way to marshal a result (with multiple rows) directly into a `[]ToDoItem{}` rather than iterating row-by-row? I can see see we have an `All()` function however it doesn't seem to work like rethinkgo (I've slightly modified the code for brevity):

``` go

        items := []TodoItem{}
        resp, err := r.Table("items").Filter(r.Row.Field("Status").Eq("complete")).OrderBy(r.Asc("Created").Run(session).All(&items)

        if err != nil {
                http.Error(w, err.Error(), http.StatusInternalServerError)
                return
        }

        ...

```

I end up with a `multiple-value ... in single-value context` error on compile. I liked this pattern as it's a useful shortcut when you want to pass a slice of structs to a handler for template rendering.

**Comment by dancannon** [comment]
I think having a method to do something like this is needed. However I am not happy with how the `All` method works I think it makes more sense to have a ScanAll method which does what you mentioned.

I will get this sorted later today.

**Comment by robert-zaremba** [comment]
In my project I have implemented `Scan`, `ScanAll`, `ScanFirst`, `Exists`, `ExistsMulti` helper functions. Example usage:

```
var products []map[string]string
err = rdbu.ScanAll(tabProduct, &products, dbsession)
var user User
notNil, err = rdbu.Scan(tabUser.GetAllByIndex("email", "email@server.com"), &user, dbsession)
```

`Scan*` automatically reflects the destination type. Furthermore `ScanAll` asserts that destination is a pointer to slice.

I can pull request them with a test suite.

**Comment by dancannon** [comment]
Could you explain `ScanFirst`, `Exists` and `ExistsMulti` first? However your `ScanAll` method would definitely be great.

**Comment by robert-zaremba** [comment]
I've created a separate issue for those helper functions, where I've attached the code:
https://github.com/dancannon/gorethink/issues/29

**Comment by dancannon** [comment]
Ok I will close this issue then.
