### ISSUE TITLE
Struct `json` fields not serializing

### ISSUE THREAD

**Issue by druska** [dancannon/gorethink#18]
Structs are being inserted into the database with the reflected field names, not the field names I define with `json`.

Example:
type CompanyResult struct {
    Name          string   `json:"name"`
    CategoryCode  string   `json:"category_code"`
    Description   string   `json:"description"`
    Permalink     string   `json:"permalink"`
}
_, err = re.Db("test").Table("company").Insert(companyResult).Run()

The database looks like this:
{"Permalink":"apple","Overview"...}

But when I scan this result and Marshal, the fields are serialized using `json` just fine. Thoughts?

**Comment by jfbus** [comment]
You will have to use "gorethink" tags (gorethink:"name").

**Comment by jfbus** [comment]
Multiple tags can be used, space-separated : `json:"name" gorethink:"name"`

**Comment by dancannon** [comment]
As GoRethink does not use encoding/json (It has its own encoder) you should use the gorethink tag instead.

For example:

``` go
type CompanyResult struct {
Name string `gorethink:"name"`
CategoryCode string `gorethink:"category_code"`
Description string `gorethink:"description"`
Permalink string `gorethink:"permalink"`
}
```

**Comment by druska** [comment]
Thanks a lot, I missed that in the docs. Hopefully this will help out other people as well.

**Comment by dancannon** [comment]
Well you raise a good point that the docs need updating to include this information. I will open another issue for this.

**Comment by chnn** [comment]
Hello,

Is there anyway I could set gorethink to use the json tags instead? In every instance when serializing a struct I am using the same tag for json as I am for gorethink. It seems it a bit redundant to define both (rethinkdb is made for storing json documents anyway.) Not big deal if no, just wondering!

**Comment by dancannon** [comment]
Hey,

Unfortunatly it is not possible to use json tags instead of the gorethink tags. As while both encoding implementations are similar the driver does some RethinkDB specific things behind the scenes. As you mention RethinkDB uses json documents however when sending queries to the database your data structures have to be converted to Datums and with the recent inclusion of pseudo types the encoding/json package doesnt work.

Hope this helps.
Daniel
