### ISSUE TITLE
Improve docs for encoding/decoding structs

### ISSUE THREAD

**Issue by dancannon** [dancannon/gorethink#19]
As mentioned by @druska it is not clear that the json tag is not longer used. 

Encoding could do with its own section in the docs to explain any how it works and how structs should be setup.

**Comment by elithrar** [comment]
If no-one else gets to this over the next week or so, I'll aim to write some docs around this. I'm porting my side-project-in-progress from rethinkgo to gorethink and will have to update my struct tags as I go anyway.

**Comment by dancannon** [comment]
@elithrar That would be great if you could do this, if you have any issues when writing up the docs let me know.

**Comment by dancannon** [comment]
Ok I have added a section for encoding and decoding structs in the readme. It is based off of the encoding/json docs since the code for encoding and decoding is also based off of encoding/json. When working on #27 I will add some examples there as well.
