### ISSUE TITLE
Add link to gowalker doc generator

### ISSUE THREAD

**Issue by robert-zaremba** [dancannon/gorethink#20]
Hi, I've imported this project into [gowalker](http://gowalker.org)

You can add a link to nicely generated docs in READMY -> [add-badge-to-your-readme](http://gowalker.org/about#add-badge-to-your-readme)

**Comment by dancannon** [comment]
I am already using godoc.org. What advantages does GoWalker have over this?

**Comment by robert-zaremba** [comment]
http://gowalker.org/about

Main differences:
- uses aggressive browser cache
- more functionality (eg in context source listing)
- different UI
- anyone can add example for a project
- supports multiple languages readme files

**Comment by dancannon** [comment]
I think I am going to stick with GoDoc for now as I dont see any significant benefits.
