### ISSUE TITLE
[Proposal] Split `RqlTerm` into more reacher types

### ISSUE THREAD

**Issue by robert-zaremba** [dancannon/gorethink#26]
In first class rethinkdb drivers (js, python, ruby) we have have more reacher types then simple expression (`RqlTerm`):
- `singleRowSelection`
- `selection`
- ....

We can slit `RqlTerm` into `RqlTerm` and `SRqlTerm` (simple/single RQL term) - this can help us construct RQL expressinos, because some of them are not valid, like:

```
row, err := r.Table("table").Get("key").Count().RunRow(s)
// err = gorethink: Expected type SEQUENCE but found SINGLE_SELECTION:
```

When `RqlTerm.Get` would return `SRqlTerm` then we can avoid such errors in runtime.

 Maybe it is worth to introduce even more types?
- `Scalar` -> is returned by expressions like `Count`, `IsEmpty`, ..

**Comment by robert-zaremba** [comment]
I've Edited description: added `Scalar` as and additional type for proposal.

**Comment by dancannon** [comment]
Ill look into how to implement this first and then get back to you

**Comment by dancannon** [comment]
I am going to leave this issue alone for now as it will require quite a lot of changes to the internal workings and I am not sure if this would work well with Go's embedding model (All of the first class drivers have object inheritance)

**Comment by robert-zaremba** [comment]
The object inheritance - does it change anything? The problem is to list a methods which should be everywhere. If we can list them, then The solution is going to be straightforward. Am I correct?

From what I see now, those methods are: `Run` and `Exec`. `RunRow` is valid only for selection/stream type, `RunWrite` works only for `object` (insert, delete...)

**Comment by dancannon** [comment]
Im going to close this because although it might be nice to add I think it will overcomplicate things.
