### ISSUE TITLE
Connection pool scheduler.

### ISSUE THREAD

**Issue by robert-zaremba** [dancannon/gorethink#28]
By now if we limit a connection pool and we want to open a new connection above `Pool.MaxActive` we get `ErrPoolExhausted` error - "gorethink: connection pool exhausted".

It would be very desirable to have a scheduler for `Pool`. It will wait for a next released connection and pass it to a next waiting request.

Proposed objectives:
- scheduler is plug-able
- default scheduler:
  - use simple LIFO scheduling
  - supports time-outs

**Comment by dancannon** [comment]
Ok ill add this to my list of stuff to look at :) 

However I think one solution would be to set the MaxActive to unlimited by default. This is similar to database/sql which creates a temporary connection if one is not available in the pool. I think setting MaxActive to 0 it should have this effect but I have to check.

Also a big disadvantage of using a scheduler is that you might end up spending more time waiting than you would setting up a connection

My question is do we need to create a scheduler or should we just do the same?

**Comment by robert-zaremba** [comment]
Actually now I'm using unlimited `MaxActive`. But it's not safe to the system when you will be bombarded with tons of requests and you will end up creating 5000 connections in a second. Also DB will suffer.

I think we can copy a solution, eg from Redis driver.

**Comment by dancannon** [comment]
Which Redis driver are you looking at? The connection pool code for this driver is actually based off of RedisGo.

**Comment by jfbus** [comment]
Why not use a buffered channel of connections ?

Free connections are sent to the channel.

If all connections are busy, the next connection request will be blocked until a connection is released.

**Comment by robert-zaremba** [comment]
@jfbus  - right.
This is exactly what I have in mind: funnel + redigo.
https://github.com/buth/funnel/blob/master/funnel.go

**Comment by dancannon** [comment]
I have changed the connection pool to use the value of 0 for MaxActive by default. This should prevent `ErrPoolExhausted`.  

While I might look at improving the connection pool code at some point I think adding a queue is overcomplicating things so I will close this issue.

Thanks for the feedback regarding this issue.
