### ISSUE TITLE
Helper functions

### ISSUE THREAD

**Issue by robert-zaremba** [dancannon/gorethink#29]
In my project I have implemented `Scan`, `ScanAll`, `ScanFirst`, `Exists`, `ExistsMulti` helper functions. Example usage:

```
var products []map[string]string
err = rdbu.ScanAll(tabProduct, &products, dbsession)
var user User
notNil, err = rdbu.Scan(tabUser.GetAllByIndex("email", "email@server.com"), &user, dbsession)
```

`Scan*` automatically reflects the destination type. Furthermore `ScanAll` asserts that destination is a pointer to slice.

It's easier to explain all of them in a code: https://gist.github.com/robert-zaremba/7115332
Each of this functions I found useful.

I can **pull request** them with a test suite.

**Comment by robert-zaremba** [comment]
What do you think? I can adapt the code an pull request it to gorethink with tests? There two option:
- directly in gorethink package
- in a subpackage (eg: gorethink/utils)

**Comment by dancannon** [comment]
I have written a similar function for `ScanAll` which uses a less refection which I am trying to avoid as much as possible (https://gist.github.com/dancannon/7115619). 

Regarding the rest of the functions I am not really sure they are needed as part of the driver (although I agree they are useful).

I will commit the code for `ScanAll` but I am open for discussion on the rest of the functions.

**Comment by robert-zaremba** [comment]
I suggest to make a validation of `dest` type in your `ScanAll` method, to set a proper error message.
The biggest reflection cost is in a loop, so it won't change the performance, but make users more happy.

###### `ScanFirst`

is usefull when you want to extract only the first element from a _selection_ type query, like in index queries: 

```
notNil, err = ScanFirst(tableTest.GetAllByIndex("email", "new@emial.com"), &dest, dbs)
```

This query won't work with a `RunRow`:

```
_, err = dbTest.GetAllByIndex("ema", "new@emial.com").RunRow(dbs)
c.Check(err, IsNil) // Fail: value gorethink.RqlDriverError = gorethink.RqlDriverError{message:"No rows in the result set"} ("gorethink: No rows in the result set")
```

###### `Scan`

comes from the inconvenient usage of RunRow/IsNil/Scan pattern (my complains in https://github.com/dancannon/gorethink/issues/11). But maybe I'm just using it incorrectly? Anyway It allows me to:

```
ok, err := Scan(tableTest.Get("id"), &dest, dbs)
if err != nil{} // db error or scan error
if ok {} // document exists, scan succeed
```

instead of:

```
row, err = tableTest.Get("id").RunRow()
if err {} // db error
if row.IsNil() {} // document doesn't exists
err = row.Scan(dest)
if err != nil {} //scan failed
```

###### `Exists` and `ExistsMulti`

are simple helper functions which implements a common pattern. The former for _singleRowSelection_ query type and the latter for _selection_ query type.

**Comment by robert-zaremba** [comment]
All in all the existence of helper functions reflects driver principles - if it should provide:
- only a low level functionality for end-users, and they will implement their higher level helper function
- or provides implementation for common patterns.

Both options are valid - your choice :)

**Comment by dancannon** [comment]
Ok so because I am trying to keep the API I am going to close this issue however I do appreciate the effort and I might do what you suggested earlier and have a utils package however I will wait until I am happy the driver is stable before I do this. 

Also regarding ScanFirst you could probably do the same thing by running RunRow and then Scan.

**Comment by elithrar** [comment]
@dancannon @robert-zaremba Thanks for working on this. 

`ScanAll` is probably one of the most common operations so glad it made the cut ;)

**Comment by dancannon** [comment]
@robert-zaremba ok it turns out my solution to ScanAll didnt actually work so I will be using your code after all. Sorry for the confusion.

**Comment by elithrar** [comment]
Also see the rethinkgo implementation, if that helps: https://github.com/christopherhesse/rethinkgo/blob/master/rows.go#L149

**Comment by robert-zaremba** [comment]
@dancannon so can I make a pull request for `ScanAll`? You want to bind it into `*ResultRows`?

Also the other functions are not bind to any structure, they are methods (so they not imply the API change).

**Comment by dancannon** [comment]
I have already sorted the code, I did bind it to ResultRows similar to keep it the same as Scan. https://github.com/dancannon/gorethink/blob/master/results.go#L176

**Comment by elithrar** [comment]
@dancannon Although this is closed, I've a question about the implementation: I just want to clarify that there isn't a shortcut for what I'm trying to achieve here.

The below is invalid: `multiple-value gorethink.Table("flatpages").Get(f.Title).Run() in single-value context`

``` go
func (f *FlatPage) Get() error {

        err := rethinkdb.Table("flatpages").Get(f.Title).RunRow(conn)

        ...
```

... however this works:

``` go
func (f *FlatPage) Get() error {

        res, err := rethinkdb.Table("flatpages").Get(f.Title).RunRow(conn)

        ...

        err := res.Scan(&f)

        ...
```

Is this right? I'm not particularly fussed either way (I can see that it helps demarcate where the error is) but now that I have some free time I'm in the process of bringing my half-completed rethinkgo stuff over to gorethink. Wanted to make sure I wasn't missing something that allowed me to use the one-liner.

**Comment by jfbus** [comment]
To be valid, the first piece of code should be :

``` go
_, err := rethinkdb.Table("flatpages").Get(f.Title).RunRow(conn)
```

or

``` go
err := rethinkdb.Table("flatpages").Get(f.Title).Exec(conn)
```

**Comment by dancannon** [comment]
Yes as @jfbus mentions if you want to run a query without waiting for a response then `Exec` is the function you should use.

There is currently no shortcut for running a query and scanning into a variable in one line.

**Comment by elithrar** [comment]
@jfbus @dancannon Great, thanks. Still need the return values (generated keys): was specifically after the whether the shortcut would work. The two-liner works well enough.

**Comment by dancannon** [comment]
If you need the generated keys then you can use the `RunWrite` function instead of `RunRow` which will scan the result into `WriteResponse`.
