### ISSUE TITLE
Using RunWrite with TableCreate doesn't provide results.

### ISSUE THREAD

**Issue by radioact1ve** [dancannon/gorethink#33]
When creating a table with RunWrite:

```
r.Db(dbName).TableCreate(tableName).RunWrite(session)
```

The results I get are:

```
{0 0 0 0 0 0 []  <nil> <nil>}
```

Even though the table is create just fine in the DB there is nothing in the results indicating it was created successfully. Could this be that WriteResponse doesn't have a Created filed?

Where I'm confused is that the docs for RunWrite state: 

```
This function should be used if you are running a write query 
(such as Insert, Update, TableCreate, etc...)
```

Not sure if this is expected behavior or just a bug in the docs. I have no problem tackling this time permitting.

**Comment by radioact1ve** [comment]
Wow I feel silly now. Just added Created filed to WriteResponse and it works as expected. Feels weird that it's to easy. 
Pull request: https://github.com/dancannon/gorethink/pull/34

**Comment by dancannon** [comment]
Haha dont worry about it, it looks to be my mistake. I will add the created field to WriteResponse right away. Thanks for letting me know.

**Comment by radioact1ve** [comment]
Bah my fault. Double check guery.go because my pull request included the Created field too. Duplicate fields.

**Comment by dancannon** [comment]
Ok I think this is all sorted now as the tests seem to be passing. Thanks again for your work.
