### ISSUE TITLE
How to use index with OrderBy?

### ISSUE THREAD

**Issue by robert-zaremba** [dancannon/gorethink#35]
Both of the following don't work:

```
OrderBy("index-name")
OrderBy(map[string]string{"index": "index-name"}) // Error: Unable to get quotes from DB gorethink: Expected type STRING but found OBJECT.
```

Where "index-name" is different then the name of each document fields.

**Comment by dancannon** [comment]
I might be completely wrong but `OrderBy("index-name")` doesnt seem to work. However I have fixed `OrderBy(map[string]string{"index": "index-name"})` .

Will push my changes in a bit.

**Comment by robert-zaremba** [comment]
Thanks.
From my tests it doesn't work. All this things makes me even more liking https://github.com/dancannon/gorethink/issues/24

**Comment by dancannon** [comment]
Am I doing something wrong here then? https://github.com/dancannon/gorethink/blob/master/query_transformation_test.go#L115

Also I will be working on changing optional arguments soon.

**Comment by robert-zaremba** [comment]
Sorry, it is working.
Thank you.

**Comment by robert-zaremba** [comment]
uhh, I'm testing it and it doesn't seems to work:

```
expr = dbQuote.Between([]interface{}{product, market},
        []interface{}{product, market, maxTime}, "index", "pro-mar-t").
        OrderBy(map[string]string{"index": "pro-mar-t"})
...
```

Unable to get quotes from DB gorethink: Expected type STRING but found OBJECT. in: 
r.OrderBy(r.Between(r.Table("quote"), ["AUSFB", "FOBAUSE"], ["AUSFB", "FOBAUSE", 17179869180], index="pro-mar-t"), {index="pro-mar-t"})

**Comment by dancannon** [comment]
That code seems to work for me so I have no idea what could be causing the issue. Could you show the whole query you are using + some example data?

**Comment by robert-zaremba** [comment]
I will try to prepare it soon.

**Comment by robert-zaremba** [comment]
I''ve spent a bit more time on this, and my problem was that I used

```
 OrderBy(map[string]string{"index": "pro-mar-t"})
```

instead of

```
 OrderBy(map[string]interface{}{"index": "pro-mar-t"})
```

I'm pull requesting an update for a function description. https://github.com/dancannon/gorethink/pull/40 

PS: I prefer the first form, since the index name is always a string.

**Comment by dancannon** [comment]
Ill look into changing it to map[string]string but I am not sure just yet.

**Comment by robert-zaremba** [comment]
The `map[string]interface{}` type is right, because we can wrap the index name with sorting order (eg: `r.Desc`) and everything works, eg:

```
OrderBy(map[string]interface{}{"index": r.Desc("pro-mar-t")})
```
