### ISSUE TITLE
multi index creation is not supported by gorethink.

### ISSUE THREAD

**Issue by robert-zaremba** [dancannon/gorethink#36]
Rethinkdb 1.10 supports multi indexes: http://www.rethinkdb.com/api/javascript/index_create/ (3rd example)

I don't see the way how to do it in gorethink.

**Comment by dancannon** [comment]
What is the issue you see with doing that in GoRethink?

**Comment by robert-zaremba** [comment]
I can't use gorethink to create an _multi index_. In JS driver it is done by:

```
r.table('dc').indexCreate('abilities', {multi:true}).run(conn, callback)
```

**Comment by dancannon** [comment]
Ah ok sorry I thought you meant that it was not possible to do that in Go. I will fix this later today.

**Comment by robert-zaremba** [comment]
Thank you. I will change a topic, it might be misleading.
