### ISSUE TITLE
Bug: `nil` doesn't work in expressions

### ISSUE THREAD

**Issue by robert-zaremba** [dancannon/gorethink#37]
The following is a valid JS RQL expression:

```
r.expr(null).eq(null)  // returns true
```

However gorethink doesn't support that:

```
row, err := rdb.Expr(nil).Eq(nil).RunRow(dbs)
```

PANIC: user_test.go:110: UsersSuite.TestTrialValidate

... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x414031)

/usr/lib/go/src/pkg/runtime/panic.c:229
  in panic
/usr/lib/go/src/pkg/runtime/panic.c:487
  in panicstring
/usr/lib/go/src/pkg/runtime/os_linux.c:236
  in sigpanic
/home/robert/.go/src/github.com/dancannon/gorethink/query_control.go:49
  in expr
/home/robert/.go/src/github.com/dancannon/gorethink/query_control.go:18
  in Expr
user_test.go:115
  in UsersSuite.TestTrialValidate

**Comment by dancannon** [comment]
Should be fixed now.

**Comment by robert-zaremba** [comment]
Thank you!
