### ISSUE TITLE
Optional arguments

### ISSUE THREAD

**Issue by dancannon** [dancannon/gorethink#4]
We need to decide on a format for doing optional arguments. As far as I can tell there are only a couple of solutions. 

Firstly we could pass a map[string]interface{} to each function that can take optional arguments. For example:

``` go
r.Js("return 1;", map[string]interface{}{"timeout": 10}
r.Js("return 1;", map[string]interface{}{}
```

Another solution would be to keep the old approach of have a function for each optional parameter. One change I would make is to change the function to only change the optional parameters of the previous term instead of changing them for the entire query. For example:

``` go
r.Js("return 1;").Timeout(10)
r.Js("return 1;")
```

Any preferences to either choice or another option?

**Comment by crosbymichael** [comment]
Maybe:

``` golang
package main

import (
        "fmt"
)

func do(cmd string, args ...interface{}) {

}

func main() {
        do(
                "return 1;",
                "timeout", 10,
                "orderby", "desc")
}
```

**Comment by dancannon** [comment]
I have implemented the method suggested by @crosbymichael as I think this keeps the API clean and as close to possible as the other drivers. In some cases I added extra functions instead for example there is now GetAll and GetAllByIndex.
