### ISSUE TITLE
How to do Upsert?

### ISSUE THREAD

**Issue by ekanna** [dancannon/gorethink#41]
Insert a new record if "id" doesn't exist. If "id" exits update it.

Do we have this Upsert method?

**Comment by elithrar** [comment]
See http://godoc.org/github.com/dancannon/gorethink#RqlTerm.Update

**Comment by robert-zaremba** [comment]
```
... Update(your_doc_specification, "upsert", true) ...
```

**Comment by ekanna** [comment]
`_, err = r.Table("mytable").Insert(doc, "upsert", true).RunWrite(session)`
This solved my issue. Thanks for your responses.

**Comment by druska** [comment]
For new people searching, this has changed to the r.InsertOpts.Upsert struct instead.

**Comment by ekanna** [comment]
Revised one

``` go
r.Table("mytable").Insert(doc, r.InsertOpts{Upsert: true}).RunWrite(session)
```

**Comment by dancannon** [comment]
Thanks for updating the issue. I have also started keeping a [change log](https://github.com/dancannon/gorethink/blob/master/CHANGELOG.md) which I will use to update people about any BC breaking changes.

**Comment by ekanna** [comment]
Revised one 

``` go
r.Table("mytable").Insert(doc, r.InsertOpts{Conflict: "update"}).RunWrite(session)
OR
r.Table("mytable").Insert(doc, r.InsertOpts{Conflict: "replace"}).RunWrite(session)
```
