### ISSUE TITLE
RunRow needs to differentiate between an error and no results

### ISSUE THREAD

**Issue by baruch** [dancannon/gorethink#43]
It is currently returning both an empty row and an error, but this makes it hard to discern between a real error (f.ex. connection lost) and just not getting any data. In the later case I prefer to just test for IsNil on the row and have err as nil.

**Comment by dancannon** [comment]
Currently the way of differentiating between an error and no results is to check if the returned error is nil before checking IsNil.

What else would you prefer?

**Comment by baruch** [comment]
That's what I tried but if the result is empty I get a non-nil error. It is
as if an empty result is an error.

**Comment by dancannon** [comment]
Could you check that you are using the latest version of the driver as the way of detecting for an empty response was changed recently. 

If you are using the latest driver could you please send me the query that you are running so that I can test what is going on.

**Comment by baruch** [comment]
The last commit I have is only one behind what's on github master branch.

I'm using a query in the form: r.Table("disks").Filter(disk).RunRow(session)
where the 'disk' object is the exact object I query in the DB but with the
Id field empty.

Baruch

**Comment by dancannon** [comment]
I apologize but I am still not following. Here is a query that attempts find a non existent document.

``` go
func (s *RethinkSuite) TestRowNotFound(c *test.C) {
    // Ensure table + database exist
    DbCreate("test").Exec(sess)
    Db("test").TableDrop("Table3").Exec(sess)
    Db("test").TableCreate("Table3").Exec(sess)

    // Test query
    query := Db("test").Table("Table3").Get("nil")
    row, err := query.RunRow(sess)
    c.Assert(err, test.IsNil)
    c.Assert(row.IsNil(), test.Equals, true)

    var response interface{}
    err = row.Scan(&response)
    c.Assert(err, test.IsNil)
    c.Assert(response, test.IsNil)
}
```

**Comment by baruch** [comment]
I added to the end of the function TestEmptyResult in results_test.c the following:

```
    var obj object;
    obj.Name = "test"
    row, err = Db("test").Table("test").Filter(obj).RunRow(sess)
    c.Assert(err, test.IsNil)
    c.Assert(row.IsNil(), test.Equals, true)
```

This fails:

```
FAIL: results_test.go:138: RethinkSuite.TestEmptyResults

results_test.go:163:
  c.Assert(err, test.IsNil)
... value gorethink.RqlDriverError = gorethink.RqlDriverError{message:"No rows in the result set"} ("gorethink: No rows in the result set")

OOPS: 140 passed, 1 FAILED
--- FAIL: Test (15.27 seconds)
```
