### ISSUE TITLE
[Bug] Decoding doesn't work for query with OrderBy & EqJoin

### ISSUE THREAD

**Issue by robert-zaremba** [dancannon/gorethink#44]
The case when it doesn't work is when we want to use `OrderBy` and `EqJoin` in the same query.
Below I'm presenting a test which proves that decoding doesn't work.

```
func (suite *DBSuite) TestOrderJoin(c *C) {
    type Map map[string]interface{}
    tab := rdb.Table("test")
    tab2 := rdb.Table("test2")
    var err error
    rdb.Db("test").TableDrop("test").Exec(dbs)
    err = rdb.Db("test").TableCreate("test").Exec(dbs)
    c.Assert(err, IsNil)
    rdb.Db("test").TableDrop("test2").Exec(dbs)
    err = rdb.Db("test").TableCreate("test2").Exec(dbs)
    c.Assert(err, IsNil)

    err = tab.Insert(Map{"S": "s1", "T": 2}).Exec(dbs)
    err = tab.Insert(Map{"S": "s1", "T": 1}).Exec(dbs)
    err = tab.Insert(Map{"S": "s1", "T": 3}).Exec(dbs)
    err = tab.Insert(Map{"S": "s2", "T": 3}).Exec(dbs)
    c.Assert(err, IsNil)

    err = tab2.Insert(Map{"id": "s1", "N": "Rob"}).Exec(dbs)
    err = tab2.Insert(Map{"id": "s2", "N": "Zar"}).Exec(dbs)
    c.Assert(err, IsNil)

    rows, err := tab.
        OrderBy("T").      // [1]
        EqJoin("S", tab2). // [2]
        Run(dbs)
    c.Assert(err, IsNil)

    var out []Map
    for rows.Next() {
        p := Map{}
        err = rows.Scan(&p)
        c.Assert(err, IsNil)  // ERROR: gorethink: cannot decode array into Go value of type main.Map
        out = append(out, p)
    }
    c.Check(len(out), Equals, 4, Commentf("%v", out))
}
```

When we comment out line [1] or [2] then everything works well.

In rethinkdb _dataexplorer_ the query works and return right value (array of maps)

**Comment by dancannon** [comment]
Ok so after running the query it turns out that the returned value of the datum is actually of type atom and not sequence and because of this and how GoRethink handles the result from the server the result is not iterable in the way you are trying.

This means that you should be running `RunRow` instead of `Run`.

**Comment by robert-zaremba** [comment]
But it is inconsistent. How `RunRow` or `Run` is depending on `OrderBy`?
When I remove `OrderBy` (1) then it works well.
Furthermore in JS driver everything works well and returns expected data (array of documents) - whenever if I use `OrderBy` or not.

**Comment by dancannon** [comment]
I dont know why when using OrderBy the query returns an Atom(A single value) but without the OrderBy it returns a sequence as this is just how RethinkDb works. Also things work in the JS driver because the code for results it structured differently.

I will look into redoing the result code but it will require a bit of work so I will not be able to do it for a couple of days. I apologize for the wait.

**Comment by robert-zaremba** [comment]
Maybe it is a RethinkDB bug?

**Comment by dancannon** [comment]
I think its just the way rethinkdb works

**Comment by robert-zaremba** [comment]
Maybe we should report this? Did you inspect the internals of that query (the datum code of response)?

**Comment by dancannon** [comment]
Ill try to talk to the guys on IRC about it. And yes basically the difference is that with OrderBy a single datum is returned of type array and without an array of datums are returned which are of type object.

As I say though it shouldn't be too difficult to get the driver to convert a single datum of type array into an iterable form.

**Comment by dancannon** [comment]
Ok so I talked to some of the guys on IRC about this issue and they let me know that the use of the OrderBy causes the query to be cached in memory and because of this the result it returned as an atom.
