### ISSUE TITLE
RethinkDB 1.11

### ISSUE THREAD

**Issue by druska** [dancannon/gorethink#48]
RethinkDB 1.11 was released today. Does gorethink pass all it's tests on 1.11? If so, maybe the version number in the README should be bumped to prevent confusion.

**Comment by dancannon** [comment]
The RethinkDB 1.11 release has a couple of RQL changes so it is probable that not all tests will pass. I will start work of updating the driver and I hope to get it all sorted today.

**Comment by dancannon** [comment]
The driver should now be updated for v1.11 . There are some internal changes that need to be made but it should now been fine to use.

I have also added the file CHANGELOG.md to show all the API changes made.
