### ISSUE TITLE
Converting a Contains Query from JS to Go

### ISSUE THREAD

**Issue by elithrar** [dancannon/gorethink#51]
I'm attempting to convert some quick and dirty search RQL from JS to Go:

``` js
r.db('demo').table('listings').filter(function(row){return
                r.expr(['title','location','company']).contains(function(key){return
                  row(key).coerceTo('string').match('(?i)'+'developer')})}) 
```

So far I have:

``` go
docs, err := rethinkdb.Table("listings").Filter(func(row rethinkdb.RqlTerm) rethinkdb.RqlTerm {
        return rethinkdb.Expr([]string{"title", "location", "company", "term"}).Contains(func(key rethinkdb.RqlTerm) rethinkdb.RqlTerm {
            return rethinkdb.Row(key).CoerceTo("string").Match("(?i)"+s).Slice(lower, upper).Run(conn)
        })
    })
```

However I get (15 being the first line; 17 the last)

```
./search.go:15: assignment count mismatch: 2 = 1
./search.go:17: cannot call non-function gorethink.Row (type gorethink.RqlTerm)
```

What am I missing here?

PS: Is there an quick way to test whether a connection to RethinkDB is active? I'd like to test this when my application starts up so I can bail out if the DB is down. `conn, err := rethinkdb.Connect(...)` doesn't seem to return an error if the connection fails.

**Comment by dancannon** [comment]
It looks like you are running the `Run` in the wrong place. You only need to do this on the outermost query. Another issue is your use of Row. You need to use `Row.Field(key)` instead of `Row(key)`.

So your code should be as follows:

``` go
docs, err := rethinkdb.Table("listings").Filter(func(row rethinkdb.RqlTerm) rethinkdb.RqlTerm {
        return rethinkdb.Expr([]string{"title", "location", "company", "term"}).Contains(func(key rethinkdb.RqlTerm) rethinkdb.RqlTerm {
            return rethinkdb.Row.Field(key).CoerceTo("string").Match("(?i)"+s).Slice(lower, upper)
        })
    }).Run(conn)
```

I hope this fixes your issue (I have not run the code myself) but let me know if not. Also I will look into the connection error stuff either today or tomorrow.

**Comment by elithrar** [comment]
@dancannon Thanks Dan—that compiles and I'll see if it works tonight. Need to hook it up to the handler.

RE: checking if a connection is "active" — `Session` has an unexported field `closed` that we could possibly check against (`if Session.Closed == false { // bail out/reconnect X times/etc }}` however that might conflict with `idleTimeout` if we don't check fast enough.

For context—I forgot that RethinkDB doesn't do passive data migrations between versions. OS X's `launchctl` was causing it to silently fail to start RethinkDB with my dev DB, but my application wasn't returning an error when trying to connect and was just starting up anyway:

``` go
var conn *rethinkdb.Session
func init() {
    var err error
    conn, err = rethinkdb.Connect(map[string]interface{}{
        "address":     config.DB.Address,
        "database":    config.DB.Name,
                // etc
    })
    if err != nil {
        logger.Fatalln(err)
    }
}
```

**Comment by dancannon** [comment]
Basically when you run connect the pool was being setup but not actually tested. I must have just overlooked this when adding the connection pool. 

I changed this by fetching a connection from the pool and making a connection to the database. This should solve the problem.

**Comment by elithrar** [comment]
@dancannon Perfect, thanks—just updated the library, killed my RethinkDB instance and now my application correctly bails out on startup.

**Comment by elithrar** [comment]
@dancannon Sorry to bump this, but (finally) getting around to this last bit of functionality and running into an issue:

The query:

``` go
docs, err := rethinkdb.Table("listings").Filter(func(row rethinkdb.RqlTerm) rethinkdb.RqlTerm {
        return rethinkdb.Expr([]string{"title", "location", "company", "term"}).Contains(func(key rethinkdb.RqlTerm) rethinkdb.RqlTerm {
            return rethinkdb.Row.Field(key).CoerceTo("string").Match("(?i)"+s).Slice(lower, upper)
        })
    }).Run(conn)
```

The error:

``` go
gorethink: Cannot use r.row in nested queries.  Use functions instead. in: "r.Filter(r.Table("listings"), func(var_3 r.RqlTerm) r.RqlTerm { return func(var_0 r.RqlTerm) r.RqlTerm { return r.Contains(["title", "location", "company", "term"], func(var_2 r.RqlTerm) r.RqlTerm { return func(var_1 r.RqlTerm) r.RqlTerm { return r.Slice(r.Match(r.CoerceTo(r.Field(r.Row, var_1), "string"), "(?i)full-time"), 0, 15) } }) } })"
```

I'm at a loss as to what's causing it.

**Comment by dancannon** [comment]
I think this should work (Not tested). The difference is that instead of using rethinkdb.Row we use the RqlTerm argument of the filter function.

``` go
    docs, err := rethinkdb.Table("listings").Filter(func(row rethinkdb.RqlTerm) rethinkdb.RqlTerm {
        return rethinkdb.Expr([]string{"title", "location", "company", "term"}).Contains(func(key rethinkdb.RqlTerm) rethinkdb.RqlTerm {
            return row.Field(key).CoerceTo("string").Match("(?i)"+s).Slice(lower, upper)
        })
    }).Run(conn)
```

**Comment by elithrar** [comment]
Almost there! It didn't work on first run, however I realised `Slice()` wasn't chained to `Filter()`. This was the corrected query:

``` go
docs, err := rethinkdb.Table("listings").Filter(func(row rethinkdb.RqlTerm) rethinkdb.RqlTerm {
        return rethinkdb.Expr([]string{"title", "location", "company", "term"}).Contains(func(key rethinkdb.RqlTerm) rethinkdb.RqlTerm {
            return row.Field(key).CoerceTo("string").Match("(?i)" + s)
        })
    }).Slice(lower, upper).Run(conn)
```

Thanks for your help @dancannon!

**Comment by dancannon** [comment]
Brilliant! Glad I could help.

**Comment by elithrar** [comment]
Out of curiosity, is there a way to turn `.Match("(?i)" + s)` into something like `.Match("(?i)").Expr(s)`?

The problem with string concatenation in `.Match` is that the string is part of the regex and therefore is brittle (`hello+there` breaks it). Technically you could strip anything that's not `unicode.IsLetter` from the input, but that's not ideal (you'd have to write your own .Strip function, for starters).

**Comment by dancannon** [comment]
`.Match(r.Expr("(?i)").Add(r.Expr(s))` might work

**Comment by elithrar** [comment]
No dice. Something like "software++++engineer” breaks it with:

``` js
gorethink: Error in regexp `(?i)software++++engineer` (portion `++`): bad repetition operator: ++ in:
r.Slice(r.Filter(r.Table("listings"), func(var_6 r.RqlTerm) r.RqlTerm { return r.Contains(["title", "location", "company",
 "term"], func(var_7 r.RqlTerm) r.RqlTerm { return r.Match(r.CoerceTo(r.Field(var_6, var_7), "string"), r.Add("(?i)", 
"software++++engineer")) }) }), 0, 15)”
```

(the extra `+` characters are being interpreted as part of the regex)

**Comment by elithrar** [comment]
One of the RethinkDB guys suggested `just doing a.upcase().eq(b.upcase()) instead of a.match("(?i)" + b)` which might solve the problem as `Eq` shouldn't be affected by any regex a user might decide to include (maliciously or otherwise).

Is there a way to restructure the query to suit?

**Comment by dancannon** [comment]
I think upcase is maybe coming in a future rethinkdb version as there are not currently any functions in the API for transforming the case of a string and I think I remember reading an issue about this. 

The only other thing I can think of is to have a separate field which contains a lowercase version of the string.

**Comment by elithrar** [comment]
Michael Lucy from RethinkDB suggested using something like `quotemeta` — I'm using Go's `regexp.QuotaMeta(s))` and it seems to be fairly robust (as in, I can't personally break it, so possibly not that robust!) for this use-case.

And they also confirmed upcase is in "next", so won't hit until 1.12 or later.
