### ISSUE TITLE
More user friendly error message will be better

### ISSUE THREAD

**Issue by AlexLuya** [dancannon/gorethink#53]
Blow is a error message I got,and with context in mind,I know some error message will be presented to me,but blow message still made me surprised.I think these are internal details of error,and if it can be "translated" into more user friendly format or style,it will save a lot of time to figure out what the real problem is.

gorethink.RqlRuntimeError{rqlResponseError:gorethink.rqlResponseError{response:(*ql2.Response)(0xc2000c8e10), term:gorethink.RqlTerm{name:"Filter", termType:39, data:interface {}(nil), args:[]gorethink.RqlTerm{gorethink.RqlTerm{name:"Table", termType:15, data:interface {}(nil), args:[]gorethink.RqlTerm{gorethink.RqlTerm{name:"", termType:1, data:"user", args:[]gorethink.RqlTerm(nil), optArgs:map[string]gorethink.RqlTerm(nil)}}, optArgs:map[string]gorethink.RqlTerm{}}, gorethink.RqlTerm{name:"{...}", termType:3, data:interface {}(nil), args:[]gorethink.RqlTerm(nil), optArgs:map[string]gorethink.RqlTerm{"email":gorethink.RqlTerm{name:"", termType:1, data:"Les Miserables", args:[]gorethink.RqlTerm(nil), optArgs:map[string]gorethink.RqlTerm(nil)}}}}, optArgs:map[string]gorethink.RqlTerm{}}}}

**Comment by dancannon** [comment]
Hi Alex, this is actually something I have been planning on working on for a while as there are a number of small issues regarding error handling and query debugging. Thanks for reminding me that I should work on it.

I will try to get this sorted out over the next couple of days.

**Comment by dancannon** [comment]
How are you checking the value of the error? Does the driver return a more friendly error message if you call the `Error` function? 

For example:

``` go
row, err := Db("test").Table("test").Run(session)
fmt.Println(err.Error())
```
