### ISSUE TITLE
ResultRows.IsNil() always return true before Next() is called?

### ISSUE THREAD

**Issue by wangbin** [dancannon/gorethink#55]
```
rows, _ := r.Table("users").Run(conn)
fmt.Println(rows.IsNil())
for rows.Next() {
    var row interface{}
    err = rows.Scan(&row)
    fmt.Println(row)
    fmt.Println(rows.IsNil())
}
fmt.Println(rows.IsNil())
```

And the result:

true
map[id:2dabdea7-e179-4311-9d06-5292c0dd46ff name:user1]
false
...
false

Even the ResultRows actually has data, the first IsNil() call returns true, is this a little confusing?

**Comment by dancannon** [comment]
Currently `IsNil` checks that the currently selected row in the result set is nil. Because `Next` is not yet called the currently selected row is by default nil. 

That being said I will look over this function and see if I can make things more consistent.

**Comment by elithrar** [comment]
I believe I'm running into this too. I have a Between query that collects unexpired posts based on the current page in the URL:

query.go

``` go
func GetPaginatedListings(page int) (listings []*Listing, paginate bool, exists bool, err error) {

    upper := page * config.Pagination.PerPage
    lower := upper - config.Pagination.PerPage

        docs, err := rethinkdb.Table("listings").Between(rethinkdb.Now(), nil, rethinkdb.BetweenOpts{
        Index: "expiry_date",
    }).OrderBy(rethinkdb.Desc("posted_date")).Slice(lower, upper+1).Run(conn)
    if err != nil {
        return listings, false, false, err
    }

        if docs.IsNil() {
            return listings, false, false, nil
        }

    err = docs.ScanAll(&listings)
    if err != nil {
        return listings, false, false, err
    }
```

handler.go

``` go
    listings, paginate, exists, err := GetPaginatedListings(num)
    if err != nil {
        serverError(w, r, err, 500)
        return
    }

    if exists == false {
        notFound(w, r)
        return
    }
```

It seems a workaround might be to check `if len(listings) == 0 { return listings, false, false, nil }` instead so I can properly detect when the result set is empty and return a 404 when someone attempts to paginate beyond that.

**Comment by dancannon** [comment]
Ok I have updated `IsNil` to work even if `Next` has not been called. However I also added a `Count` function which counts the number of results returned from the server and stored in the cache. 

Now instead of doing `len(listings) == 0` you could do `count, _ := docs.Count(); count == 0`

**Comment by elithrar** [comment]
Great, thanks Dan!
