### ISSUE TITLE
Inserts get truncated data at high concurrency

### ISSUE THREAD

**Issue by pengux** [dancannon/gorethink#56]
I'm playing around with the driver at runtime.GOMAXPROCS(8) and trying to insert 29k documents using this [Zip JSON](http://media.mongodb.org/zips.json). After a while, the driver gives this error at random location and stop

```
gorethink: String `CALCASIEU` (truncated) contains NULL byte at offset 9. in:
r.Insert(r.Table("zips"), {City="CALCASIEU\x00", Loc=[-91.875149, 31.906412], Pop=124, State="LA"})
```

Although everything runs fine at runtime.GOMAXPROCS(4) and rethinkdb get to around 3k of inserts/sec. The sample code is here (http://play.golang.org/p/ye2BpuJzlE)

**Comment by dancannon** [comment]
Hi,

Unfortunately I cannot replicate this issue, I have tried with code with multiple values for GOMAXPROCS and the channel size. The error about null terminated strings comes from RethinkDB and I cant think of why this driver would add the null byte to the end of the string. Could be this an issue with the json package?

Also as a side note for anybody who uses goroutines and gets the error "connection is reset by peer" try limiting the number of concurrent goroutines. In @pengux's code he uses a channel of size 1000 however on my laptop I had to  reduce this so 200.

**Comment by pengux** [comment]
Hi @dancannon,

were you able to run with GOMAXPROCS >= 8?

**Comment by dancannon** [comment]
Unfortunately my PC only has 4 cores so I was not able to test with anything higher than 4. (I tried `runtime.GOMAXPROCS(8)` and this works however I think it just defaults the value to 4 in this case)

**Comment by pengux** [comment]
@dancannon I can give you access to a VPS with 8 cores for you to play with if you want to look further into this issue?

**Comment by dancannon** [comment]
That would be great my email is danielATdanielcannonDOTcoDOTuk

**Comment by pengux** [comment]
Sent an email to you now

**Comment by dancannon** [comment]
Hmm ok so I am not sure if this fixes the issue but once I made the following change the error message stopped appearing. The change I made was I moved the `zip` variable declaration inside the goroutine. I assume this fixes the issue by stopping the memory being overwitten but this is only a guess.

**Comment by pengux** [comment]
@dancannon Can you try the code here too http://play.golang.org/p/OnG_Z6tx2_, it's the same code but without the race condition.

A side note is that if I increase the GOMAXPROCS to 8, the Mongodb inserts went down from 9 secs to only 5 secs while the Rethinkdb insert still stays around 21-22 secs. Maybe it has something to do with the connection pool?

**Comment by dancannon** [comment]
I made a couple of changes (http://play.golang.org/p/onr4_iu1qV) and the code now seems to work just fine. Also I am not sure what I changed but it now takes ~10s which is more reasonable and @neumino got similar results using the JS driver.

**Comment by pengux** [comment]
Did you made changes in the driver or do you mean in the test code? Because the http://play.golang.org/p/onr4_iu1qV still gives me roughly the same results, with 22-23 sec for the inserts...

**Comment by dancannon** [comment]
Hmm I made the changes to the test code and I just ran through the test code again 5 times and no errors occurred and all were below 10 seconds.

**Comment by pengux** [comment]
The results didn't really change for me. After a reboot of server, the execution time went down to around 12-13 secs for Rethinkdb inserts, but Mongodb also went down to around 5-6 secs so there is still a big difference between the two. Can you try to add the Mongodb inserts into the same test code and compare it?

**Comment by dancannon** [comment]
So are you still getting null terminated string errors? I have run the code multiple times now and I don't get the error anymore. As mentioned I am aware of the performance issues but I do not have the time to fix this at the moment.

**Comment by pengux** [comment]
No, I haven't received it anymore. It was probably fixed by fixing the race condition. Which parts do you think can be easily optimized, maybe I can help?

**Comment by dancannon** [comment]
Honestly I am not sure where the issues are at the moment so I need to first check that out. Thanks for the offer though.

**Comment by dancannon** [comment]
Ok so I think you should get performance closer to mongodb if you use the Exec function instead of RunWrite. This causes the query not to wait for a response from the server and allows you to quickly insert documents.

Here is an example of what I mean: http://play.golang.org/p/laKnNjsXiU

**Comment by pengux** [comment]
What's the results for you when changed to Exec? In my test it's still the same unfortunately...

**Comment by dancannon** [comment]
Ah my mistake I have just pushed some changes to the driver. If you update you should get some better times. However it takes some time for RethinkDB to handle the insertions even after your program has finished inserting.

After spending some time looking at the performance of the driver I think that the reasons for the slow insertion times are due to RethinkDB and not this driver, that being said I plan to talk to the official devs to make sure I have not made a mistake somewhere.

**Comment by pengux** [comment]
Nice work! The inserts of Rethinkdb stays around 6-7 seconds now. But one question is that using Exec doesn't give me the generated IDs back, would it be possible to do the same optimization for the Run*() methods?

**Comment by elithrar** [comment]
The trade-off with Exec is that it's fast because it doesn't acknowledge
writes. This was (and is?) MongoDB's default mode, hence why it's so fast.
If you're not acknowledging your writes, you are possibly ignoring
failures. You also can't get generated IDs back, because you're not waiting
for their return. You could possibly generate your own IDs, but this
doesn't address the underlying issue (that the record might not be inserted
properly).

RethinkDB won't be as fast as MongoDB when both are in their default modes,
but RethinkDB gives you consistency that MongoDB doesn't.

**Comment by pengux** [comment]
The test script is using mgo's Insert() for Mongodb and you're probably right about that it doesn't support write concerns AFAIK. Just hoping that there are room left for improvement of the Rethinkdb driver's Insert() also and I know that @dancannon and the Rethinkdb devs are looking into this.
