### ISSUE TITLE
Example for Append()?

### ISSUE THREAD

**Issue by spielstein** [dancannon/gorethink#58]
I'm trying to Append() to an embedded array like this:

```
row, err := r.Table("things").
    Get(thingId).
    Field("array").
    Append(map[string]string{"tag": "value"}).
    RunWrite(dbSession)

"array": [ ]    ->    "array": [ {"tag": "value"} ]
```

... it does not work; the array remains empty. What am I doing wrong?

**Comment by spielstein** [comment]
Solved -- this is it:

```
row, err := r.Table("things").Get(thingId).
    Update(map[string]interface{}{"array": r.Row.Field("array").
    Append(map[string]string{"tag": "value"})}).
    RunWrite(dbSession)
```

**Comment by aeneasr** [comment]
I tried the same thing but for some reason `Changes().Run` doesn't get fired. Any ideas?

**Comment by dancannon** [comment]
Hi, could you please post the code you are trying to run?

**Comment by aeneasr** [comment]
Sure, thanks for the quick reply :)
- [Schema](https://github.com/ory-am/hydra/blob/a26d9252a0ae924c37b955cf49000550b50d0b1f/jwk/manager_rethinkdb.go#L93-L96)
- [Append item to array](https://github.com/ory-am/hydra/blob/a26d9252a0ae924c37b955cf49000550b50d0b1f/jwk/manager_rethinkdb.go#L120-L126)
- [Delete item from array](https://github.com/ory-am/hydra/blob/a26d9252a0ae924c37b955cf49000550b50d0b1f/jwk/manager_rethinkdb.go#L138-L143)
- [Watcher](https://github.com/ory-am/hydra/blob/a26d9252a0ae924c37b955cf49000550b50d0b1f/jwk/manager_rethinkdb.go#L160-L193)

**Comment by aeneasr** [comment]
I forgot to add:

```
fmt.Printf("row: %v", row)
```

gives

```
row: {0 0 0 0 1 0 0 0 0 0 0 0 0 0 []  [] []}
```

Which equals to `row.Replaced = 1`

**Comment by aeneasr** [comment]
The update term looks like:

``` go
    if row, err := m.Table.Get(set).Update(func(d r.Term) interface{} {
        ret := map[string]interface{}{
            "keys": d.Field("keys").Append([]interface{}{keys}...),
        }
        fmt.Printf("Updating: %v", ret) // map[keys:var_0.Field("keys").Append([{Algorithm="", Use="", Key={N={}, E=65537}, KeyID="public"}])]
        return ret
    }).RunWrite(m.Session); err != nil {
              // ...
```

**Comment by dancannon** [comment]
I can't see anything that looks obviously wrong but I will have a proper look when I get home from work this evening. If you create a changes query in the RethinkDB admin UI does it show the updates?

**Comment by arekkas** [comment]
unfortunately I'm spinning up a docker rethink db image for automated testing and I need some work to do for this to be done manually. The [insert command](https://github.com/ory-am/hydra/blob/refactor/jwk/manager_rethinkdb.go#L109-L115) fires a change as expected. Is there maybe something like an index I need to create in order for array changes to be processed?

**Comment by arekkas** [comment]
I refactored the code to not use embedded arrays but rather regular documents and encountered the same issue. Missing error handlers caused the error to be ignored and not printed. In general, it is very hard to track down the error as there's some magic going on (LastErr is overriden several times?).

I believe that the error is caused by a `MarshalJSON` method receiver on `DefaultPolicy.Conditions`. The referred map was nil.

**Comment by arekkas** [comment]
The error I was able to recover by injecting some good old `log.Printf("%s", err)` inside of `Cursor.nextLocked` which got me something like: `Cannot marshal type x into type z`. However, `Cursor.Err()` resulted in an `EOF` error.

**Comment by aeneasr** [comment]
Scrap my last comments (I deleted them). Still investigating.

**Comment by aeneasr** [comment]
> I can't see anything that looks obviously wrong but I will have a proper look when I get home from work this evening. If you create a changes query in the RethinkDB admin UI does it show the updates?

This will take some time until I have it up and running in a non-automated test environment.

**Comment by dancannon** [comment]
I tried creating a very simple example based on your code and it appears to work so my guess is that either your application is creating data in a way that is incompatible with GoRethink or your changes query is setup slightly wrong. Hopefully if you can setup a non-automated test environment we should be able to get a better idea about what is going on.

Here is the code I am running, let me know if you think I have replicated something incorrectly.

``` go
package main

import (
    "encoding/json"
    "fmt"
    "github.com/davecgh/go-spew/spew"
    "time"

    r "github.com/dancannon/gorethink"
)

type rethinkSchema struct {
    KID string          `gorethink:"id"`
    Set string          `gorethink:"set"`
    Key json.RawMessage `gorethink:"key"`
}

func main() {
    sess, err := r.Connect(r.ConnectOpts{
        Addresses: []string{
            "localhost:28015",
        },
    })
    if err != nil {
        fmt.Printf("Connection Failed [ERR: %s]", err.Error())
    }

    r.DB("test").TableDrop("test58").Exec(sess)
    r.DB("test").TableCreate("test58").Exec(sess)

    connections, err := r.DB("test").Table("test58").Changes().Run(sess)
    if err != nil {
        panic(err.Error())
    }

    go func() {
        for {
            var update map[string]*rethinkSchema
            for connections.Next(&update) {
                spew.Dump(update)
            }

            connections.Close()
            if connections.Err() != nil {
                panic(connections.Err().Error())
            }

            connections, err = r.DB("test").Table("test58").Changes().Run(sess)
            if err != nil {
                panic(err.Error())
            }
        }
    }()

    resp, err := r.DB("test").Table("test58").Insert(&rethinkSchema{
        KID: "abc",
        Set: "def",
    }).RunWrite(sess)

    spew.Dump(resp, err)

    resp, err = r.DB("test").Table("test58").Insert(&rethinkSchema{
        KID: "abc",
        Set: "def",
    }).RunWrite(sess)

    spew.Dump(resp, err)

    time.Sleep(5 * time.Second)
}
```

**Comment by aeneasr** [comment]
Hey @dancannon sorry, I accidentally didn't link the commit but rather the branch head. I resolved the issue by removing the embedded array. Sorry for the inconvenience

Here are the original code lines:
- [Schema](https://github.com/ory-am/hydra/blob/a26d9252a0ae924c37b955cf49000550b50d0b1f/jwk/manager_rethinkdb.go#L93-L96)
- [Append item to array](https://github.com/ory-am/hydra/blob/a26d9252a0ae924c37b955cf49000550b50d0b1f/jwk/manager_rethinkdb.go#L120-L126)
- [Delete item from array](https://github.com/ory-am/hydra/blob/a26d9252a0ae924c37b955cf49000550b50d0b1f/jwk/manager_rethinkdb.go#L138-L143)
- [Watcher](https://github.com/ory-am/hydra/blob/a26d9252a0ae924c37b955cf49000550b50d0b1f/jwk/manager_rethinkdb.go#L160-L193)
