### ISSUE TITLE
No way to control field naming of an external struct

### ISSUE THREAD

**Issue by tmc** [dancannon/gorethink#60]
It would be nice to provide an alternate way (other than struct tagging) to control the Field name mapping behavior.

Defining an interface that the encoding package would use is a possible approach.

``` go
type RethinkFieldMapper interface {
    RethinkFieldMap() map[string]string
}
```

?

**Comment by dancannon** [comment]
What advantages would this have over tagging? This approach seems far more verbose.

**Comment by tmc** [comment]
The use case here is that of not having control of struct definitions that you want to store via gorethink. Sorry for not making that clear before.

**Comment by dancannon** [comment]
Ok thanks for the use case it makes much more sense. 

I will look into how this can be implemented but I might not be able to look at it for a week or so.

**Comment by tmc** [comment]
Nice work. Well done.
