### ISSUE TITLE
Compound indexes don't work, and have no test coverage

### ISSUE THREAD

**Issue by wildattire** [dancannon/gorethink#65]
It seems that GetAllByIndex() using a compound index returns 0 rows no matter what. Using a single secondary index works fine, and using a compound index in the rethink data explorer works.

I also don't see any place in the test suite that actually validates it, either. I see two tests of GetAllByIndex() in query_select_test.go, but neither one of them tests compound indexes.

**Comment by robert-zaremba** [comment]
@wildattire - can you share some code, where it doesn't work?

**Comment by dancannon** [comment]
So I had a go at setting up compound indexes. It seems that RethinkDB needs the indexes created in a very specific format. I took this as an excuse to setup some examples which I have been meaning to do for a while and have added a test as well. 

Here is the compound index example: http://godoc.org/github.com/dancannon/gorethink#example-RqlTerm-GetAll-Compound

**Comment by wildattire** [comment]
@robert-zaremba sure.

I Created the index with this( either node.js driver or rethinkdb data explorer ):

r.db('foo').table('bar').indexCreate('userstatus', [r.row('user_id'), 
        r.row('status')])

When I issue the query in data explorer:

r.db('foo').table('bar').getAll(['58bfcdbc38824ada41cb9ea37211762f', 100], {index:'userstatus'})

I get the rows I'm looking for. However, issuing the same query with the gorethink driver returns 0 rows:

```
    ....
rows, err := r.Table("bar").GetAllByIndex("userstatus", []interface{}{"58bfcdbc38824ada41cb9ea37211762f", 100}).Run(session)
if err != nil {
    return err
}
    list := make([]Bar{},0)
rows.ScanAll(list)
    ....
```

**Comment by wildattire** [comment]
@dancannon allright, we'll try different index creations methods.

**Comment by wildattire** [comment]
Ok, we deleted and recreated our indexes and now it's working. Additionally, our _initial_ mistake was assuming that because the method signature for keys was variadic (keys ...interface{}), we'd be able to pass them in variadically. It doesn't work that way - it only works when passed as a []interface{}

Thanks guys, and sorry for the waste. But at least you got more test coverage out of it :)

**Comment by dancannon** [comment]
Not a problem, Honestly I made the same mistake when I tried to get it working :D And as you mention we now have more tests and documentation.
