### ISSUE TITLE
json tag doesn't work

### ISSUE THREAD

**Issue by AlexLuya** [dancannon/gorethink#68]
I have struct like this,

```
type Comment struct {
   Id                   string `json:"id,omitempty"`
   Name             string
   SessionId        string `json:"-"`
}
```

and want to ignore the field:SessionId by json tag,but,still, SessionId will be saved just like other fields,why?

**Comment by elithrar** [comment]
Use the `gorethink` tag as per the docs.

**Comment by AlexLuya** [comment]
Thanks,where is this(I mean replacing "json" with "gorething") documented?

**Comment by dancannon** [comment]
You can find that in the Readme(https://github.com/dancannon/gorethink#encodingdecoding-structs)

**Comment by AlexLuya** [comment]
Thanks
