### ISSUE TITLE
scan failed when null in slice

### ISSUE THREAD

**Issue by xuyu** [dancannon/gorethink#69]
![image](https://f.cloud.github.com/assets/919424/2457169/f2bd8330-af2f-11e3-98f8-1151042fb5ad.png)

got error:
{}reflect: call of reflect.Value.Interface on zero Value

**Comment by dancannon** [comment]
Could you please let me know what type are you trying to Scan in to and what query you are running?

**Comment by xuyu** [comment]
just query getAll like: 

rows, err := r.DB().Table().Run(session)
...
var data []map[string]interface{}
err := rows.ScanAll(&data)

**Comment by dancannon** [comment]
Ok that should now be fixed. Thanks for reporting the issue.
