### ISSUE TITLE
Support for v.1.12

### ISSUE THREAD

**Issue by zbindenren** [dancannon/gorethink#71]
Would be great: https://gist.github.com/coffeemug/9518214

Thanks for the great work.

**Comment by dancannon** [comment]
Hi, thanks for submitting this issue. Unfortunately I am busy for the next 2 weeks so I will not be able to update to 1.12 just yet.

If any body else has time that would be great otherwise I will get round to it as soon as I have the time

**Comment by oderwat** [comment]
Just want to tell you that I "wait" for that too and appreciate your work a lot!

I would contribute / help a bit but I am still fighting my way into GoLang! Maybe in the future!

**Comment by dancannon** [comment]
Thank you very much, glad to hear it!

I am still busy this week (Completing my dissertation) but next week I am free.

**Comment by dancannon** [comment]
I am starting work on this now. I will log my progress here.

Tasks:
- [x] Update protobuf file
- [x] Remove `GroupBy`
- [x] Remove `GroupedMapReduce`
- [x] Remove `Avg`
- [x] Remove `Sum`
- [x] Remove `r.Count`
- [x] Removed base parameter for `Reduce` 
- [x] Add `Object`
- [x] Add `Upcase`
- [x] Add `Downcase`
- [x] Add `Split`
- [x] Add `GROUPED_DATA` pseudotype
- [x] Add `Group`
- [x] Add `Ungroup`
- [x] Add new aggregators
- [x] Update tests  for `GroupedMapReduce`

I also plan to make the following changes which are not relevant to 1.12:
- [x] Convert connection arguments to a struct
- [x] Fix query printing

**Comment by oderwat** [comment]
Looks good! Thank you for the update!

**Comment by dancannon** [comment]
I have pushed an early version to the v0.2 branch.
