### ISSUE TITLE
Merging into empty array causes an error

### ISSUE THREAD

**Issue by jhvst** [dancannon/gorethink#74]
So I have this relatively simple query which fetches two tables and joins them together. The query runs successfully in RethinkDB dataexplorer, with syntax like this:

```
r.db(db).table("users").get("7f8d9b62-6e2b-4d88-a465-c4db7a2fd10e").merge({"posts":r.db(db).table("posts").filter(
  function(user) {
    return user("author").eq("7f8d9b62-6e2b-4d88-a465-c4db7a2fd10e")
  }
).coerceTo("array")})
```

The resulted raw output looks like this:

```
{"email":"example@mailinator.com","id":"7f8d9b62-6e2b-4d88-a465-c4db7a2fd10e","name":"Juuso","posts":[{"Content":"Lorem ipsum","Time":238579237,"author":"7f8d9b62-6e2b-4d88-a465-c4db7a2fd10e","title":"Example"}]}
```

However, when run in Go with query:

```
row, err := r.Db(db).Table("users").Get(person.Id).Merge(map[string]interface{}{"posts":r.Db(db).Table("posts").Filter(func (post r.RqlTerm) r.RqlTerm {
    return post.Field("author").Eq(person.Id)
}).CoerceTo("ARRAY")}).RunRow(s)
```

I get an error:

```
gorethink: Cannot perform merge on a non-object non-sequence `null`.
```

Without the merge the empty array "posts" is rendered as null in JSON, so I believe that that's the problem. Also, I'm not sure whether the query on Go is right, so that may be the reason as well.

The struct for person is the following:

```
type Person struct {
    Id       string `json:"id"`
        ...
    Posts    []Post `json:"posts"`
}
```

Any idea whether the problem is in the library or my code?

**Comment by dancannon** [comment]
I have tried to replicate this issue but I am not having much success. 

Would it be possible to have a look at the data in your users/posts tables or at least a sample of them?

**Comment by jhvst** [comment]
My users table:

```
[{"email":"juuso@mail.com","id":"7f8d9b62-6e2b-4d88-a465-c4db7a2fd10e","name":"Juuso Haavisto","posts":[]}]
```

My posts table:

```
[{"author":"7f8d9b62-6e2b-4d88-a465-c4db7a2fd10e","content":"Lorem ipsum dolem hual","title":"Lorem"}]
```

[The whole function to retrieve the data](https://github.com/9uuso/vertigo/blob/master/users.go#L11)

[The structs](https://github.com/9uuso/vertigo/blob/master/main.go#L17)

[The route which fails to render](https://github.com/9uuso/vertigo/blob/master/main.go#L202)

**Comment by dancannon** [comment]
Thanks, ill have a look into this.

**Comment by dancannon** [comment]
I have replicated your issue as best I can and I still get the correct result.  As far as I can tell this is not an issue with the decoder but an error returned by RethinkD, this should mean that the error is being caused by an invalid query or invalid data.

Just to confirm when you remove the merge from the Go query the posts field is nil?

**Comment by jhvst** [comment]
Alright, I both reinstalled this driver and nuked my database and now the issue seems to be fixed. The online UI reported my table to have 5 times the documents it should have had, so something must gone wrong at some point. The driver actually returned "not found" when using the plain Get, but the data explorer returned the document as it would have worked all the time. I'm bit confused, but at least it works now...

I appreciate your time and willingness to help. The next time I'll open issue ticket I'll make sure to delete my database first.
