### ISSUE TITLE
Support for binary ([]byte) data

### ISSUE THREAD

**Issue by timshannon** [dancannon/gorethink#76]
Currently rethinkdb doesn't support a binary datatype (rethinkdb/rethinkdb#137), and to get around it, most people are simply encoding to base64.

Until rethinkdb supports it, it could be supported natively in this driver by looking for []byte types in the encode/decode process and translating it to/from base64.

**Comment by dancannon** [comment]
I agree this would be a good feature, I will start looking into how I can implement this.

**Comment by dancannon** [comment]
OK so I have had a look at this and I have come across an issue. 

Encoding []byte using base64 is pretty straightforward however decoding is not so easy as there is no easy way to check if a string should be decoded (I know I could use regexp to match a string however I am not totally happy with this either). My other idea was to use struct tags however this also doesnt cover all the cases,

Unless anybody else has any suggestions I think it might be for the best to wait for RethinkDB to implement a binary datatype.

**Comment by timshannon** [comment]
Yep, makes sense. I might take a stab at it,see if I can come up with something. Thanks.

**Comment by dancannon** [comment]
For now I think it might make more sense to implement this in your own application rather than in the database driver.

**Comment by dancannon** [comment]
The official drivers have started to be updated to use the new JSON api so I am going to close this issue as the encoder package will need to be redone then anyway and I don't really want to add a feature that will be this short lived.

**Comment by mark-kubacki** [comment]
RethinkDB 1.14 introduced (a) binary data type.
