### ISSUE TITLE
Peculiar behavior

### ISSUE THREAD

**Issue by acasanova** [dancannon/gorethink#85]
I just picked up on a weird behavior using gorethink and beego web framework.
Below is a screenshot of my logs when retrieving an image object. The field in question is specialty_ids. For some reason it switches to a prior update value everytime i refresh the view.  When I use the Data Explorer I get specialty_ids:"231,49" everytime.  When I looked more closely it seems like there were some extra fields added to the record.  In the screenshot from the Data Explorer there were lowercase duplicate fields added. Is my struct not properly formatted?

![image](https://cloud.githubusercontent.com/assets/2922800/2907637/b8e5eef2-d61e-11e3-89ae-4d9ba1154965.png)

This is the retrieval code

```

/*
GetImageByID Get IMage Meta Data
*/
func (im *ImageService) GetImageByID(imageID int64) Image {
    rows, err := r.Table("images").Get(imageID).RunRow(session)
    if err != nil {
        fmt.Println(err)
    }

    var res Image
    err = rows.Scan(&res)
    if err != nil {
        log.Fatalln(err)
    }
    fmt.Println("Just Got the specialty IDS", res.Specialty_ids)
    return res
}

```

Here is the struct

```
type Image struct {
    Prod_Code     string
    Prod_Title    string
    Filename      string
    Height        int
    Id            int64
    Keyword_ids   string
    Keywordlist   string
    Keywords      string
    Mime          string
    Name          string
    Path          string
    Specialties   string
    Specialty_ids string
    Timestamp     string
    Width         int
}
```

**Comment by dancannon** [comment]
Hi,

I think this might be happening because you have not been using struct tags. Could you try changing your struct definition to the following and let me know if anything changes.

``` go
type Image struct {
    Id            string `gorethink:"id,omitempty"`
    Prod_Code     string  `gorethink:"prod_code"`
    Prod_Title    string   `gorethink:"prod_title"`
    Filename      string  `gorethink:"filename"`
    Height        int  `gorethink:"height"`
    Keyword_ids   string  `gorethink:"keyword_ids"`
    Keywordlist   string  `gorethink:"keywordlist"`
    Keywords      string  `gorethink:"keywords"`
    Mime          string  `gorethink:"mime"`
    Name          string  `gorethink:"name"`
    Path          string  `gorethink:"path"`
    Specialties   string  `gorethink:"specialties"`
    Specialty_ids string  `gorethink:"speciality_ids`
    Timestamp     string  `gorethink:"timestamp"`
    Width         int  `gorethink:"width"`
}
```

I am unsure as to how GoRethink created the lowercase fields without these struct tags. Could you let me know if you modified the table outside of your Go application at all? If you have not then there might be an issue with the encoding package. 

Thanks,
Daniel

**Comment by acasanova** [comment]
I hadn't changed the table structure outside of the application.
Here is the update function. It takes some json data and attempts to find the record and then update it

```
/*
UpdateSpecialties updates specific image specialties
*/
func (ic *ImageController) UpdateSpecialties() {

    req := struct {
        ID          int64
        Specialties []string
    }{}

    if err := json.Unmarshal(ic.Ctx.Input.RequestBody, &req); err != nil {
        fmt.Println(err)
        ic.Ctx.Output.SetStatus(400)
        ic.Ctx.Output.Body([]byte("Error Json"))
        return
    }

    //Get image and update specialty list
    imageObj := is.GetImageByID(req.ID)
    imageObj.Specialty_ids = strings.Join(req.Specialties, ",")
    is.Update(imageObj)
    ic.Data["json"] = true
    ic.ServeJson()
}


/*
Update updates image
*/
func (im *ImageService) Update(image Image) {
    fmt.Println("Before Update", image.Specialty_ids)
    var err error
    _, err = r.Table("images").Get(image.Id).Update(image).RunWrite(session)
    if err != nil {
        fmt.Println(err)
    }
}
```

**Comment by acasanova** [comment]
Is it better practice to keep my field names all lowercase without camelcase?  I added the struct tags as you advised( both lower case and camel case) and I receive the same behavior which is that I get duplicate fields after an update.

I'll try another experiment with all lowercase field names and post my findings.

**Comment by acasanova** [comment]
So I
1. Re-imported the data with all lowercase field names
2. Updated the struct tags to proper field names

Now for some reason my updates do not work after adding the struct tags. Not sure what I'm missing. Removing the struct tags updates the record but adds duplicate capitalized fields.

Below is a screenshot of the logs right before the update and after a refresh of the page. The field to look for is the specialty_ids field.  

![image](https://cloud.githubusercontent.com/assets/2922800/2917077/c0e43cd2-d6c1-11e3-9d81-18bfdcea6688.png)

```
/*
Update updates image
*/
func (im *ImageService) Update(image Image) {
    fmt.Println("Before Update: specialty_ids\n", image.Specialty_ids)

    res, err := r.Table("images").Get(image.Id).Update(image).Run(session)
    if err != nil {
        panic(err)
    }
    fmt.Println(res)
}
```

**Comment by dancannon** [comment]
Hmm this is really quite odd, I can definitely see that `Specialty_ids` is not being encoded properly but I cannot think of any reason why this would happen. Also as far as I am aware RethinkDB skips a write if it does not change anything.

There may be an issue with the encoder and I was actually planning on replacing this soon with github.com/mitchellh/mapstructure. Since I cannot replicate this could you check the result of encoding your struct. Could you please run this code in your `Update` method. (You may need to `go get` the spew package. 

``` go
import "github.com/dancannon/gorethink/encoding"
import "github.com/davecgh/go-spew/spew"

data, err := encoding.Encode(image)
spew.Dump(image, data, err)
```

Also just to check are you using v0.2.1 of the driver?

EDIT: changed code slightly

**Comment by acasanova** [comment]
I updated the code first and re-ran the scenario but there was no change.
I then pulled the spew library and tried your code. Here are the results. It looks like the image object is updated with the proper data right the update query. 

![image](https://cloud.githubusercontent.com/assets/2922800/2918238/1749f75e-d6ce-11e3-9d8a-744454531302.png)

**Comment by acasanova** [comment]
I'm sorry I overlooked the fact that I changed the id field to string type. So that explains the update skipping. Once i changed the field type back to int64 the update occured but added the "Specialty_ids" Struct Field to the record instead of updating "specialty_ids". Hopefully the console dump helps you.

**Comment by dancannon** [comment]
Im really sorry but I made a change to my code example. Could you dump the input image as well please? I should hopefully then have enough to figure out what is going wrong.

**Comment by acasanova** [comment]
Sorry, I missed that.

![image](https://cloud.githubusercontent.com/assets/2922800/2918606/f58d167e-d6d1-11e3-85ff-1f87fa53f395.png)

I tried updating the "keyword_ids" field thinking maybe the underscore was an issue but I was able to update that field. Odd

![image](https://cloud.githubusercontent.com/assets/2922800/2918622/1844b686-d6d2-11e3-8b5d-33b23811157c.png)

**Comment by dancannon** [comment]
Sorry about that I had a typo on the speciality IDs field. Try changing

``` go
Specialty_ids string `gorethink:"speciality_ids`
```

to

``` go
Specialty_ids string `gorethink:"speciality_ids"`
```

**Comment by acasanova** [comment]
Thanks, that fixed it.
