### ISSUE TITLE
Optional field and partial update

### ISSUE THREAD

**Issue by ghost** [dancannon/gorethink#86]
Good day.

Is there a way to workaround the issue of partial update with optional fields.
Here is an example:

Say, we have the following structure:

``` go
type User struct {
    Id string
    Fullname string // **Optional field**
    ApprovedAt time.Time
}
```

The list of use cases includes:
1) Insert / read the whole structure
2) Update `Fullname` only
3) Update `ApprovedAt` only

So, it can be easily inserted (**use case No.1**) in this way:

``` go
r.Db("test").Table("users").Insert(User{
    Fullname: "John Doe",
    ApprovedAt: time.Now(),
})
```

However, it is just not that easy to update either `Fullname` or `ApprovedAt` separately (**use cases No.2, 3**).

1) If we are using `omitempty` parameter for them, we can write:

``` go
r.Db("test").Table("users").Get(id).Update(User{
    ApprovedAt: time.Now(),
})
```

And the `Fullname` field will not be affected.

2) However, the `Fullname` field is optional. That means it can contain empty string. Thus, if we are trying to apply:

``` go
r.Db("test").Table("users").Get(id).Update(User{
    Fullname: "",
})
```

We expect `Fullname` to be equal to `""`. But as we are using `omitempty`, it ignores the value.

So how can we allow empty values and still update only part of the document?

**Comment by dancannon** [comment]
Thanks for the issue. I have thought about this before and I don't think there is a good solution to your issue with GoRethinks current tag system. The way I get around this is by using a `map[string]interface{}` as it allows you full control of what fields should be included.

**Comment by timshannon** [comment]
I was just going to say the same thing.  I have a generic type for this that I use:

```
type Data map[string]interface{}
```

**Comment by ghost** [comment]
@dancannon , @timshannon :+1: 
_Didn't expect to get answer so soon._

**Comment by nimajalali** [comment]
I usually use a pointer to a string in the struct definition.

It's a little more cumbersome to init but works well. 

```
type User struct {
    Id         string
    Fullname   *string `gorethink:",omitempty"`
    ApprovedAt time.Time
}
```

If Fullname is nil omitempty flag will not pass it. However if it's initialized to "" it will be passed.

To set it to "John Doe"

```
    fullName := new(string) // Empty string ""
    *fullName = "John Doe"

    r.Db("test").Table("users").Insert(User{
        Fullname:   fullName,
        ApprovedAt: time.Now(),
    })
```

To set it to empty string ""

```
        fullName := new(string) // Empty string ""

    r.Db("test").Table("users").Get(id).Update(User{
        Fullname: fullName,
    })
```
