### ISSUE TITLE
omitEmpty, uncomparable type panic.

### ISSUE THREAD

**Issue by nullboundary** [dancannon/gorethink#87]
Hi, 

I have a set of complex nested struct data, that I am inserting into rethinkdb. 

Here is a playground link of what my data looks like, and demonstrates it being unmarshalled by the go json package:
http://play.golang.org/p/NqlABINBey

When I try the same with gorethinkdb it works fine unless I add omitempty to the type "foodstructure". Then I get the following runtime panic. This could be simply my error, but since the JSON library seems to have no issues with it, I suspect its a bug in gorethink. 

```
panic: "comparing uncomparable type main.foodStructure

/usr/local/go/src/pkg/runtime/panic.c:248 (0x16f76)
    panic: runtime·newstackcall(d->fn, (byte*)d->args, d->siz);
/Users/n/Documents/Development/gospace/src/github.com/dancannon/gorethink/encoding/encoder.go:22 (0x1b4338)
    com/dancannon/gorethink/encoding.func.001: panic(r)
/usr/local/go/src/pkg/runtime/panic.c:248 (0x16f76)
    panic: runtime·newstackcall(d->fn, (byte*)d->args, d->siz);
/usr/local/go/src/pkg/runtime/iface.c:613 (0xe1f3)
    ifaceeq1: runtime·panic(err);
/usr/local/go/src/pkg/runtime/iface.c:641 (0xe340)
    efaceeq_c: return ifaceeq1(e1.data, e2.data, e1.type);
/usr/local/go/src/pkg/runtime/iface.c:656 (0xe3e5)
    efaceeq: ret = runtime·efaceeq_c(e1, e2);
/Users/n/Documents/Development/gospace/src/github.com/dancannon/gorethink/encoding/encoder.go:161 (0x1b370b)
    com/dancannon/gorethink/encoding.isEmptyValue: return v.Interface() == reflect.Zero(v.Type()).Interface()
/Users/n/Documents/Development/gospace/src/github.com/dancannon/gorethink/encoding/encoder.go:68 (0x1b3381)
    com/dancannon/gorethink/encoding.encode: if !fv.IsValid() || f.omitEmpty && isEmptyValue(fv) {
/Users/n/Documents/Development/gospace/src/github.com/dancannon/gorethink/encoding/encoder.go:32 (0x1b1f11)
    com/dancannon/gorethink/encoding.Encode: val, err := encode(reflect.ValueOf(v))
/Users/n/Documents/Development/gospace/src/github.com/dancannon/gorethink/query_control.go:76 (0x8a57a)
    com/dancannon/gorethink.expr: data, err := encoding.Encode(val)
/Users/n/Documents/Development/gospace/src/github.com/dancannon/gorethink/query_control.go:19 (0x8a04d)
    com/dancannon/gorethink.Expr: return expr(value, 20)
/Users/n/Documents/Development/gospace/src/github.com/dancannon/gorethink/query_utils.go:67 (0x9452b)
    com/dancannon/gorethink.funcWrap: val := Expr(value)
/Users/n/Documents/Development/gospace/src/github.com/dancannon/gorethink/query_write.go:31 (0x94950)
    com/dancannon/gorethink.RqlTerm.Insert: return newRqlTermFromPrevVal(t, "Insert", p.Term_INSERT, []interface{}{funcWrap(arg)}, opts)
```

**Comment by dancannon** [comment]
Hi I apologise it took so long to reply to your issue. I created a test to try and replicate your issue but could not seem to get the driver to panic. 

Here is the code I was using: https://gist.github.com/dancannon/487d90e73f8c77a011ed

Are you trying to pass the byte array to GoRethink? If so this is probably the issue as byte arrays are not supported by RethinkDB. If not could you show the code that you are using that causes the issue with GoRethink?

**Comment by nullboundary** [comment]
Hi, No problem we are all busy. 

Here is a gist that replicates the issue. https://gist.github.com/slugmobile/a872b9d0554e6ede8257

I am not trying to pass a byte array, at least my struct data does not contain one. 

 Since I am passing in a struct instead of a map, perhaps this issue concerns how gorethink encodes the struct to a map, in the function Insert()? 

I am also a little unclear about the difference between Expr() and Insert(). I am using Insert in my code as it seemed to be correct for what I was trying to do. Is Expr() a better option?

**Comment by ghost** [comment]
> I am also a little unclear about the difference between Expr() and Insert(). I am using Insert in my code as it seemed to be correct for what I was trying to do. Is Expr() a better option?

Hey, @slugmobile. `Expr()` and `Insert()` are absolutely different things. `Expr()` [just converts](https://github.com/dancannon/gorethink/blob/master/query_control.go#L18) any value to an expression. While `Insert()` obviously inserts.

So, that part of your code responsible for writing the result looks OK. @dancannon uses `Expr()` just to illustrate that you are able to use whatever `Expr` you like.

As for the issue, I faced the same one. But as for inserts I'm using a technique which is described [here](https://github.com/dancannon/gorethink/issues/86) the problem has been mostly mitigated.

**Comment by dancannon** [comment]
Thanks for adding that extra bit of code, There was an issue with one of the comparisons when using `omitempty`. To fix this I replaced the comparison with `DeepEquals`.

**Comment by nullboundary** [comment]
@anonx. Thanks for the clarification, I will have to read up on `Expr()` a bit more in the rethinkdb docs. 
@dancannon. Glade I could help fix the bug. Thanks for all your great work on the driver!
