### ISSUE TITLE
Don't break name, keep rethinkgo.

### ISSUE THREAD

**Issue by robert-zaremba** [dancannon/gorethink#9]
This driver is based on Christopher Hesse's RethinkGo.
Is there any reason to break history and introduce new driver name and confuse community?

What I see is that this driver just continue development of rethinkgo.

**Comment by dancannon** [comment]
My reasoning behind changing the name was that there are quite a few API changes and a lot of the internal workings have changed. 

I think if @christopherhesse has stopped working on his driver and is ok with linking this repo in his README then the name can be changed back to rethinkgo otherwise I believe it makes sense to keep them seperate.

**Comment by elithrar** [comment]
Agreed with Dan.

Christopher hasn't abandoned his driver—it just seems that he's extremely busy. The driver still works under 1.9, and if/when development continues these drivers are likely to approval future changes differently. 

(connection pooling is a good example: rethinkgo dropped an included implementation of it a while back)

**Comment by christopherhesse** [comment]
I'll link to dan's from my README, but the name should probably be different to avoid confusion.

**Comment by dancannon** [comment]
Ok thanks for that, I agree that the name should stay the same so I will close this issue.

**Comment by robert-zaremba** [comment]
Fair enough.
A note (eg in README) explaining about relation to _rethinkgo_ and the differences will be appreciate.

Thank you for considering this issue.

**Comment by dancannon** [comment]
Well it says "based off of Christopher Hesse's RethinkGo driver." I think that should be enough.

**Comment by robert-zaremba** [comment]
To make it more clear I would explain in few words why we have a different driver.
