### ISSUE TITLE
Secondary index for embeded struct

### ISSUE THREAD

**Issue by theaidem** [dancannon/gorethink#90]
Hi Everyone, this is an example JSON  row
{
    "id":  "da684235-eb3c-40a2-8271-35540853fd02" ,
    "email":  "email@gmail.com",
    "password": "password" ,
    "settings": {
        "lang": 1,
        "is_active": false ,
    } ,
} 

How can I create secondary index for "is_active" field? I need example, please

**Comment by timshannon** [comment]
Generally the syntax will follow closely to the main javascript API (http://www.rethinkdb.com/api/javascript/) but for specific Go examples, you can always look at the test scenarios.  An example of creating a secondary index is here: https://github.com/dancannon/gorethink/blob/master/example_query_select_test.go

That being said, it's not usually a good idea put a secondary index on a Boolean.  A Boolean can only have one of two values (true or false), so it'll never be very unique.  Best case scenario has half your table matching to true, and the other half to false, which means at a minimum you're reading half your table.

**Comment by theaidem** [comment]
Thanks for reply Tim. Actualy the example is't a real project, and I will not create indexes for bool fields.
Please see another example:

<pre>
{
    "id":  "17556624-54ca-40d7-b418-25c44d1c8563"
    "credentials": {
        "password": "$s0$fe34$rXH" ,
        "username":  "max"
    } ,
    "details": {
        "email":  "max@power.com" ,
        "first_name":  "Max" ,
        "last_name":  "Power" ,
        "phone":  ""
    },
}
</pre>

On JS I can create index for embeded field "username" like this:

<pre>r.table('users').indexCreate('username', function(row){return row('credentials')('username');})</pre>

But how to do it with Go, don't understand

<pre>   
r.Db("test").Table("users").IndexCreateFunc("username", func(row r.RqlTerm) interface{} {
        return []interface{}{???}
    }).Run(sess)</pre>

**Comment by ghost** [comment]
@theaidem, your function should return `row.Field("credentials").Field("username")`.

**Comment by theaidem** [comment]
Oh my inattention, thank you
