### ISSUE TITLE
RethinkDB 1.13

### ISSUE THREAD

**Issue by ghost** [dancannon/gorethink#91]
RethinkDB 1.13 release is ready. The list of changes includes:
- New `changes` command for subscribing to document changes on tables
- New `http` command for seamlessly pulling data from external APIs into RethinkDB

Is anybody already working on this? If so, please let me know.

**Comment by dancannon** [comment]
I plan on starting work on updating the driver to include support for the new JSON protocol later today however if anybody would like to work on the other changes that would be fantastic.

I will create separate issues for each new feature so people do not work on the same features.

**Comment by ghost** [comment]
If you don't mind I'll implement it. I've already started.

**Comment by dancannon** [comment]
Sure that would be great. Let me know if you have any questions. 

Also feel free to get rid of the encoding package if you can think of a better way of dealing with pseudo-types.

**Comment by sym3tri** [comment]
Looks like this should've been closed but wasn't.

Quick question: are these changes backwards compatible with Rethink v1.12.x?

**Comment by dancannon** [comment]
Thanks I will close this now.

I am not 100% sure if this version is backwards compatible but in general RethinkDB changes the API quite a bit.  For example when I implement the JSON protocol, the driver will definitely not be backward compatible.

Hopefully this should change with the release of v2.0.
