### ISSUE TITLE
Changefeeds

### ISSUE THREAD

**Issue by dancannon** [dancannon/gorethink#92]
RethinkDB 1.13 added changefeeds.

> RethinkDB now supports changefeeds! There’s a new term r.changes, and a new ResponseType SUCCESS_FEED.  SUCCESS_FEED is analogous to SUCCESS_PARTIAL but for feeds. The only difference is that a SUCCESS_FEED response is sometimes empty (although it would be good to write code that assumes SUCCESS_PARTIAL can be empty too). We differentiate the two because changefeeds are usually infinite, and your driver might want to handle them differently from normal streams.

**Comment by dancannon** [comment]
I think this is going to require some changes to the result handling code since `Next` returns a boolean if there are most results in the result set, this does not work so well with an infinite result set. 

Although it would still be possible to write code like this:

``` go
for {
    if rows.Next() {
        // code
    }
}
```

I think it would make more sense to add a blocking function call which waits for a response.

@anonx what do you think?

**Comment by ghost** [comment]
> I think it would make more sense to add a blocking function call which waits for a response.

Entirely agree. That kind of behavior would be closer to that one described in the [official docs](http://rethinkdb.com/docs/changefeeds/):

> The changes command returns a RethinkDB cursor, and like any cursor you can iterate through its contents in your driver. However, unlike other cursors, the cursor returned by the changes command doesn't terminate — when you iterate through all the elements, the cursor blocks until more elements are available.

**Comment by dancannon** [comment]
I have instead updated the `Next` function to block if a feed is returned. This is closer to the official drivers and does not require any API changes.

**Comment by aviz** [comment]
How do you stop the query execution ? if i call Close while Next is blocking, there is a panic because  close called twice (once to stop the Next blocking and one Next itself called as result of the other close)
