### ISSUE TITLE
RethinkDB 1.13 - JSON protocol

### ISSUE THREAD

**Issue by dancannon** [dancannon/gorethink#95]
Update the driver to use the new JSON protocol

> We’ve learned over the past few years that protobuf support in languages besides C++ is usually spotty. Third-party protobuf libraries are usually optimized for small messages (which is fair given the intended use of protobufs), and tend to fall down when sending large RethinkDB queries. Slow and buggy protobuf libraries have been causing a huge amount of pain for both users and developers.
> 
> Starting with RethinkDB 1.13, we now support an alternate JSON protocol. Yes, you can remove your protobuf dependency entirely! The old protobuf protocol still works in 1.13, but we’re planning to deprecate it once enough third-party drivers have moved to the JSON protocol.
> 
> There’s a document on the new JSON protocol at http://rethinkdb.com/docs/driver-spec/ . A lot of the specific documentation is still in the ql2.proto file, but we’re slowly moving more and more of it into the driver-spec doc, and driver-spec should have everything you need to port your driver if it’s already working with protobufs.

**Comment by robert-zaremba** [comment]
Does protobufs protocol supporting in pair with JSON one make a lot of problem to rethinkdb team? protobufs are faster and smaller (data transfer) then JSON. And protobufs support in Go is really good.

**Comment by dancannon** [comment]
I think the RethinkDB team is planning on removing protobufs so in my opinion it makes more sense to just switch to JSON.
